// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: push.proto
#ifndef GRPC_push_2eproto__INCLUDED
#define GRPC_push_2eproto__INCLUDED

#include "push.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace push {

class PushService final {
 public:
  static constexpr char const* service_full_name() {
    return "push.PushService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status PushMsg(::grpc::ClientContext* context, const ::push::PushMsgReq& request, ::push::PushMsgResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::push::PushMsgResp>> AsyncPushMsg(::grpc::ClientContext* context, const ::push::PushMsgReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::push::PushMsgResp>>(AsyncPushMsgRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::push::PushMsgResp>> PrepareAsyncPushMsg(::grpc::ClientContext* context, const ::push::PushMsgReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::push::PushMsgResp>>(PrepareAsyncPushMsgRaw(context, request, cq));
    }
    virtual ::grpc::Status DelUserPushToken(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq& request, ::push::DelUserPushTokenResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::push::DelUserPushTokenResp>> AsyncDelUserPushToken(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::push::DelUserPushTokenResp>>(AsyncDelUserPushTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::push::DelUserPushTokenResp>> PrepareAsyncDelUserPushToken(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::push::DelUserPushTokenResp>>(PrepareAsyncDelUserPushTokenRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void PushMsg(::grpc::ClientContext* context, const ::push::PushMsgReq* request, ::push::PushMsgResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PushMsg(::grpc::ClientContext* context, const ::push::PushMsgReq* request, ::push::PushMsgResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DelUserPushToken(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq* request, ::push::DelUserPushTokenResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DelUserPushToken(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq* request, ::push::DelUserPushTokenResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::push::PushMsgResp>* AsyncPushMsgRaw(::grpc::ClientContext* context, const ::push::PushMsgReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::push::PushMsgResp>* PrepareAsyncPushMsgRaw(::grpc::ClientContext* context, const ::push::PushMsgReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::push::DelUserPushTokenResp>* AsyncDelUserPushTokenRaw(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::push::DelUserPushTokenResp>* PrepareAsyncDelUserPushTokenRaw(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status PushMsg(::grpc::ClientContext* context, const ::push::PushMsgReq& request, ::push::PushMsgResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::push::PushMsgResp>> AsyncPushMsg(::grpc::ClientContext* context, const ::push::PushMsgReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::push::PushMsgResp>>(AsyncPushMsgRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::push::PushMsgResp>> PrepareAsyncPushMsg(::grpc::ClientContext* context, const ::push::PushMsgReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::push::PushMsgResp>>(PrepareAsyncPushMsgRaw(context, request, cq));
    }
    ::grpc::Status DelUserPushToken(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq& request, ::push::DelUserPushTokenResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::push::DelUserPushTokenResp>> AsyncDelUserPushToken(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::push::DelUserPushTokenResp>>(AsyncDelUserPushTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::push::DelUserPushTokenResp>> PrepareAsyncDelUserPushToken(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::push::DelUserPushTokenResp>>(PrepareAsyncDelUserPushTokenRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void PushMsg(::grpc::ClientContext* context, const ::push::PushMsgReq* request, ::push::PushMsgResp* response, std::function<void(::grpc::Status)>) override;
      void PushMsg(::grpc::ClientContext* context, const ::push::PushMsgReq* request, ::push::PushMsgResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DelUserPushToken(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq* request, ::push::DelUserPushTokenResp* response, std::function<void(::grpc::Status)>) override;
      void DelUserPushToken(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq* request, ::push::DelUserPushTokenResp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::push::PushMsgResp>* AsyncPushMsgRaw(::grpc::ClientContext* context, const ::push::PushMsgReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::push::PushMsgResp>* PrepareAsyncPushMsgRaw(::grpc::ClientContext* context, const ::push::PushMsgReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::push::DelUserPushTokenResp>* AsyncDelUserPushTokenRaw(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::push::DelUserPushTokenResp>* PrepareAsyncDelUserPushTokenRaw(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PushMsg_;
    const ::grpc::internal::RpcMethod rpcmethod_DelUserPushToken_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status PushMsg(::grpc::ServerContext* context, const ::push::PushMsgReq* request, ::push::PushMsgResp* response);
    virtual ::grpc::Status DelUserPushToken(::grpc::ServerContext* context, const ::push::DelUserPushTokenReq* request, ::push::DelUserPushTokenResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_PushMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PushMsg() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PushMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMsg(::grpc::ServerContext* /*context*/, const ::push::PushMsgReq* /*request*/, ::push::PushMsgResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPushMsg(::grpc::ServerContext* context, ::push::PushMsgReq* request, ::grpc::ServerAsyncResponseWriter< ::push::PushMsgResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DelUserPushToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DelUserPushToken() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_DelUserPushToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DelUserPushToken(::grpc::ServerContext* /*context*/, const ::push::DelUserPushTokenReq* /*request*/, ::push::DelUserPushTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDelUserPushToken(::grpc::ServerContext* context, ::push::DelUserPushTokenReq* request, ::grpc::ServerAsyncResponseWriter< ::push::DelUserPushTokenResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PushMsg<WithAsyncMethod_DelUserPushToken<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_PushMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PushMsg() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::push::PushMsgReq, ::push::PushMsgResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::push::PushMsgReq* request, ::push::PushMsgResp* response) { return this->PushMsg(context, request, response); }));}
    void SetMessageAllocatorFor_PushMsg(
        ::grpc::MessageAllocator< ::push::PushMsgReq, ::push::PushMsgResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::push::PushMsgReq, ::push::PushMsgResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PushMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMsg(::grpc::ServerContext* /*context*/, const ::push::PushMsgReq* /*request*/, ::push::PushMsgResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PushMsg(
      ::grpc::CallbackServerContext* /*context*/, const ::push::PushMsgReq* /*request*/, ::push::PushMsgResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DelUserPushToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DelUserPushToken() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::push::DelUserPushTokenReq, ::push::DelUserPushTokenResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::push::DelUserPushTokenReq* request, ::push::DelUserPushTokenResp* response) { return this->DelUserPushToken(context, request, response); }));}
    void SetMessageAllocatorFor_DelUserPushToken(
        ::grpc::MessageAllocator< ::push::DelUserPushTokenReq, ::push::DelUserPushTokenResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::push::DelUserPushTokenReq, ::push::DelUserPushTokenResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DelUserPushToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DelUserPushToken(::grpc::ServerContext* /*context*/, const ::push::DelUserPushTokenReq* /*request*/, ::push::DelUserPushTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DelUserPushToken(
      ::grpc::CallbackServerContext* /*context*/, const ::push::DelUserPushTokenReq* /*request*/, ::push::DelUserPushTokenResp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_PushMsg<WithCallbackMethod_DelUserPushToken<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_PushMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PushMsg() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PushMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMsg(::grpc::ServerContext* /*context*/, const ::push::PushMsgReq* /*request*/, ::push::PushMsgResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DelUserPushToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DelUserPushToken() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_DelUserPushToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DelUserPushToken(::grpc::ServerContext* /*context*/, const ::push::DelUserPushTokenReq* /*request*/, ::push::DelUserPushTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_PushMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PushMsg() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_PushMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMsg(::grpc::ServerContext* /*context*/, const ::push::PushMsgReq* /*request*/, ::push::PushMsgResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPushMsg(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DelUserPushToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DelUserPushToken() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_DelUserPushToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DelUserPushToken(::grpc::ServerContext* /*context*/, const ::push::DelUserPushTokenReq* /*request*/, ::push::DelUserPushTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDelUserPushToken(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PushMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PushMsg() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PushMsg(context, request, response); }));
    }
    ~WithRawCallbackMethod_PushMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMsg(::grpc::ServerContext* /*context*/, const ::push::PushMsgReq* /*request*/, ::push::PushMsgResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PushMsg(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DelUserPushToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DelUserPushToken() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DelUserPushToken(context, request, response); }));
    }
    ~WithRawCallbackMethod_DelUserPushToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DelUserPushToken(::grpc::ServerContext* /*context*/, const ::push::DelUserPushTokenReq* /*request*/, ::push::DelUserPushTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DelUserPushToken(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PushMsg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PushMsg() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::push::PushMsgReq, ::push::PushMsgResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::push::PushMsgReq, ::push::PushMsgResp>* streamer) {
                       return this->StreamedPushMsg(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PushMsg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PushMsg(::grpc::ServerContext* /*context*/, const ::push::PushMsgReq* /*request*/, ::push::PushMsgResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPushMsg(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::push::PushMsgReq,::push::PushMsgResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DelUserPushToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DelUserPushToken() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::push::DelUserPushTokenReq, ::push::DelUserPushTokenResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::push::DelUserPushTokenReq, ::push::DelUserPushTokenResp>* streamer) {
                       return this->StreamedDelUserPushToken(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DelUserPushToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DelUserPushToken(::grpc::ServerContext* /*context*/, const ::push::DelUserPushTokenReq* /*request*/, ::push::DelUserPushTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDelUserPushToken(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::push::DelUserPushTokenReq,::push::DelUserPushTokenResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_PushMsg<WithStreamedUnaryMethod_DelUserPushToken<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_PushMsg<WithStreamedUnaryMethod_DelUserPushToken<Service > > StreamedService;
};

}  // namespace push


#endif  // GRPC_push_2eproto__INCLUDED
