// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_push_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_push_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "sdkws.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_push_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_push_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_push_2eproto;
namespace push {
class DelUserPushTokenReq;
struct DelUserPushTokenReqDefaultTypeInternal;
extern DelUserPushTokenReqDefaultTypeInternal _DelUserPushTokenReq_default_instance_;
class DelUserPushTokenResp;
struct DelUserPushTokenRespDefaultTypeInternal;
extern DelUserPushTokenRespDefaultTypeInternal _DelUserPushTokenResp_default_instance_;
class PushMsgReq;
struct PushMsgReqDefaultTypeInternal;
extern PushMsgReqDefaultTypeInternal _PushMsgReq_default_instance_;
class PushMsgResp;
struct PushMsgRespDefaultTypeInternal;
extern PushMsgRespDefaultTypeInternal _PushMsgResp_default_instance_;
}  // namespace push
PROTOBUF_NAMESPACE_OPEN
template<> ::push::DelUserPushTokenReq* Arena::CreateMaybeMessage<::push::DelUserPushTokenReq>(Arena*);
template<> ::push::DelUserPushTokenResp* Arena::CreateMaybeMessage<::push::DelUserPushTokenResp>(Arena*);
template<> ::push::PushMsgReq* Arena::CreateMaybeMessage<::push::PushMsgReq>(Arena*);
template<> ::push::PushMsgResp* Arena::CreateMaybeMessage<::push::PushMsgResp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace push {

// ===================================================================

class PushMsgReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:push.PushMsgReq) */ {
 public:
  inline PushMsgReq() : PushMsgReq(nullptr) {}
  ~PushMsgReq() override;
  explicit PROTOBUF_CONSTEXPR PushMsgReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PushMsgReq(const PushMsgReq& from);
  PushMsgReq(PushMsgReq&& from) noexcept
    : PushMsgReq() {
    *this = ::std::move(from);
  }

  inline PushMsgReq& operator=(const PushMsgReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline PushMsgReq& operator=(PushMsgReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PushMsgReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const PushMsgReq* internal_default_instance() {
    return reinterpret_cast<const PushMsgReq*>(
               &_PushMsgReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PushMsgReq& a, PushMsgReq& b) {
    a.Swap(&b);
  }
  inline void Swap(PushMsgReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PushMsgReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PushMsgReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PushMsgReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PushMsgReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PushMsgReq& from) {
    PushMsgReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PushMsgReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "push.PushMsgReq";
  }
  protected:
  explicit PushMsgReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserIDsFieldNumber = 3,
    kConversationIDFieldNumber = 2,
    kMsgDataFieldNumber = 1,
  };
  // repeated string userIDs = 3;
  int userids_size() const;
  private:
  int _internal_userids_size() const;
  public:
  void clear_userids();
  const std::string& userids(int index) const;
  std::string* mutable_userids(int index);
  void set_userids(int index, const std::string& value);
  void set_userids(int index, std::string&& value);
  void set_userids(int index, const char* value);
  void set_userids(int index, const char* value, size_t size);
  std::string* add_userids();
  void add_userids(const std::string& value);
  void add_userids(std::string&& value);
  void add_userids(const char* value);
  void add_userids(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& userids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_userids();
  private:
  const std::string& _internal_userids(int index) const;
  std::string* _internal_add_userids();
  public:

  // string conversationID = 2;
  void clear_conversationid();
  const std::string& conversationid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_conversationid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_conversationid();
  PROTOBUF_NODISCARD std::string* release_conversationid();
  void set_allocated_conversationid(std::string* conversationid);
  private:
  const std::string& _internal_conversationid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_conversationid(const std::string& value);
  std::string* _internal_mutable_conversationid();
  public:

  // .sdkws.MsgData msgData = 1;
  bool has_msgdata() const;
  private:
  bool _internal_has_msgdata() const;
  public:
  void clear_msgdata();
  const ::sdkws::MsgData& msgdata() const;
  PROTOBUF_NODISCARD ::sdkws::MsgData* release_msgdata();
  ::sdkws::MsgData* mutable_msgdata();
  void set_allocated_msgdata(::sdkws::MsgData* msgdata);
  private:
  const ::sdkws::MsgData& _internal_msgdata() const;
  ::sdkws::MsgData* _internal_mutable_msgdata();
  public:
  void unsafe_arena_set_allocated_msgdata(
      ::sdkws::MsgData* msgdata);
  ::sdkws::MsgData* unsafe_arena_release_msgdata();

  // @@protoc_insertion_point(class_scope:push.PushMsgReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> userids_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr conversationid_;
    ::sdkws::MsgData* msgdata_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_push_2eproto;
};
// -------------------------------------------------------------------

class PushMsgResp final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:push.PushMsgResp) */ {
 public:
  inline PushMsgResp() : PushMsgResp(nullptr) {}
  explicit PROTOBUF_CONSTEXPR PushMsgResp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PushMsgResp(const PushMsgResp& from);
  PushMsgResp(PushMsgResp&& from) noexcept
    : PushMsgResp() {
    *this = ::std::move(from);
  }

  inline PushMsgResp& operator=(const PushMsgResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline PushMsgResp& operator=(PushMsgResp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PushMsgResp& default_instance() {
    return *internal_default_instance();
  }
  static inline const PushMsgResp* internal_default_instance() {
    return reinterpret_cast<const PushMsgResp*>(
               &_PushMsgResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PushMsgResp& a, PushMsgResp& b) {
    a.Swap(&b);
  }
  inline void Swap(PushMsgResp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PushMsgResp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PushMsgResp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PushMsgResp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const PushMsgResp& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const PushMsgResp& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "push.PushMsgResp";
  }
  protected:
  explicit PushMsgResp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:push.PushMsgResp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_push_2eproto;
};
// -------------------------------------------------------------------

class DelUserPushTokenReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:push.DelUserPushTokenReq) */ {
 public:
  inline DelUserPushTokenReq() : DelUserPushTokenReq(nullptr) {}
  ~DelUserPushTokenReq() override;
  explicit PROTOBUF_CONSTEXPR DelUserPushTokenReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DelUserPushTokenReq(const DelUserPushTokenReq& from);
  DelUserPushTokenReq(DelUserPushTokenReq&& from) noexcept
    : DelUserPushTokenReq() {
    *this = ::std::move(from);
  }

  inline DelUserPushTokenReq& operator=(const DelUserPushTokenReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline DelUserPushTokenReq& operator=(DelUserPushTokenReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DelUserPushTokenReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const DelUserPushTokenReq* internal_default_instance() {
    return reinterpret_cast<const DelUserPushTokenReq*>(
               &_DelUserPushTokenReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(DelUserPushTokenReq& a, DelUserPushTokenReq& b) {
    a.Swap(&b);
  }
  inline void Swap(DelUserPushTokenReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DelUserPushTokenReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DelUserPushTokenReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DelUserPushTokenReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DelUserPushTokenReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DelUserPushTokenReq& from) {
    DelUserPushTokenReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DelUserPushTokenReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "push.DelUserPushTokenReq";
  }
  protected:
  explicit DelUserPushTokenReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserIDFieldNumber = 1,
    kPlatformIDFieldNumber = 2,
  };
  // string userID = 1;
  void clear_userid();
  const std::string& userid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_userid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_userid();
  PROTOBUF_NODISCARD std::string* release_userid();
  void set_allocated_userid(std::string* userid);
  private:
  const std::string& _internal_userid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_userid(const std::string& value);
  std::string* _internal_mutable_userid();
  public:

  // int32 platformID = 2;
  void clear_platformid();
  int32_t platformid() const;
  void set_platformid(int32_t value);
  private:
  int32_t _internal_platformid() const;
  void _internal_set_platformid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:push.DelUserPushTokenReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr userid_;
    int32_t platformid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_push_2eproto;
};
// -------------------------------------------------------------------

class DelUserPushTokenResp final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:push.DelUserPushTokenResp) */ {
 public:
  inline DelUserPushTokenResp() : DelUserPushTokenResp(nullptr) {}
  explicit PROTOBUF_CONSTEXPR DelUserPushTokenResp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DelUserPushTokenResp(const DelUserPushTokenResp& from);
  DelUserPushTokenResp(DelUserPushTokenResp&& from) noexcept
    : DelUserPushTokenResp() {
    *this = ::std::move(from);
  }

  inline DelUserPushTokenResp& operator=(const DelUserPushTokenResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline DelUserPushTokenResp& operator=(DelUserPushTokenResp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DelUserPushTokenResp& default_instance() {
    return *internal_default_instance();
  }
  static inline const DelUserPushTokenResp* internal_default_instance() {
    return reinterpret_cast<const DelUserPushTokenResp*>(
               &_DelUserPushTokenResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(DelUserPushTokenResp& a, DelUserPushTokenResp& b) {
    a.Swap(&b);
  }
  inline void Swap(DelUserPushTokenResp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DelUserPushTokenResp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DelUserPushTokenResp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DelUserPushTokenResp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const DelUserPushTokenResp& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const DelUserPushTokenResp& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "push.DelUserPushTokenResp";
  }
  protected:
  explicit DelUserPushTokenResp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:push.DelUserPushTokenResp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_push_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PushMsgReq

// .sdkws.MsgData msgData = 1;
inline bool PushMsgReq::_internal_has_msgdata() const {
  return this != internal_default_instance() && _impl_.msgdata_ != nullptr;
}
inline bool PushMsgReq::has_msgdata() const {
  return _internal_has_msgdata();
}
inline const ::sdkws::MsgData& PushMsgReq::_internal_msgdata() const {
  const ::sdkws::MsgData* p = _impl_.msgdata_;
  return p != nullptr ? *p : reinterpret_cast<const ::sdkws::MsgData&>(
      ::sdkws::_MsgData_default_instance_);
}
inline const ::sdkws::MsgData& PushMsgReq::msgdata() const {
  // @@protoc_insertion_point(field_get:push.PushMsgReq.msgData)
  return _internal_msgdata();
}
inline void PushMsgReq::unsafe_arena_set_allocated_msgdata(
    ::sdkws::MsgData* msgdata) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.msgdata_);
  }
  _impl_.msgdata_ = msgdata;
  if (msgdata) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:push.PushMsgReq.msgData)
}
inline ::sdkws::MsgData* PushMsgReq::release_msgdata() {
  
  ::sdkws::MsgData* temp = _impl_.msgdata_;
  _impl_.msgdata_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::sdkws::MsgData* PushMsgReq::unsafe_arena_release_msgdata() {
  // @@protoc_insertion_point(field_release:push.PushMsgReq.msgData)
  
  ::sdkws::MsgData* temp = _impl_.msgdata_;
  _impl_.msgdata_ = nullptr;
  return temp;
}
inline ::sdkws::MsgData* PushMsgReq::_internal_mutable_msgdata() {
  
  if (_impl_.msgdata_ == nullptr) {
    auto* p = CreateMaybeMessage<::sdkws::MsgData>(GetArenaForAllocation());
    _impl_.msgdata_ = p;
  }
  return _impl_.msgdata_;
}
inline ::sdkws::MsgData* PushMsgReq::mutable_msgdata() {
  ::sdkws::MsgData* _msg = _internal_mutable_msgdata();
  // @@protoc_insertion_point(field_mutable:push.PushMsgReq.msgData)
  return _msg;
}
inline void PushMsgReq::set_allocated_msgdata(::sdkws::MsgData* msgdata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.msgdata_);
  }
  if (msgdata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(msgdata));
    if (message_arena != submessage_arena) {
      msgdata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, msgdata, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.msgdata_ = msgdata;
  // @@protoc_insertion_point(field_set_allocated:push.PushMsgReq.msgData)
}

// string conversationID = 2;
inline void PushMsgReq::clear_conversationid() {
  _impl_.conversationid_.ClearToEmpty();
}
inline const std::string& PushMsgReq::conversationid() const {
  // @@protoc_insertion_point(field_get:push.PushMsgReq.conversationID)
  return _internal_conversationid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PushMsgReq::set_conversationid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.conversationid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:push.PushMsgReq.conversationID)
}
inline std::string* PushMsgReq::mutable_conversationid() {
  std::string* _s = _internal_mutable_conversationid();
  // @@protoc_insertion_point(field_mutable:push.PushMsgReq.conversationID)
  return _s;
}
inline const std::string& PushMsgReq::_internal_conversationid() const {
  return _impl_.conversationid_.Get();
}
inline void PushMsgReq::_internal_set_conversationid(const std::string& value) {
  
  _impl_.conversationid_.Set(value, GetArenaForAllocation());
}
inline std::string* PushMsgReq::_internal_mutable_conversationid() {
  
  return _impl_.conversationid_.Mutable(GetArenaForAllocation());
}
inline std::string* PushMsgReq::release_conversationid() {
  // @@protoc_insertion_point(field_release:push.PushMsgReq.conversationID)
  return _impl_.conversationid_.Release();
}
inline void PushMsgReq::set_allocated_conversationid(std::string* conversationid) {
  if (conversationid != nullptr) {
    
  } else {
    
  }
  _impl_.conversationid_.SetAllocated(conversationid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.conversationid_.IsDefault()) {
    _impl_.conversationid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:push.PushMsgReq.conversationID)
}

// repeated string userIDs = 3;
inline int PushMsgReq::_internal_userids_size() const {
  return _impl_.userids_.size();
}
inline int PushMsgReq::userids_size() const {
  return _internal_userids_size();
}
inline void PushMsgReq::clear_userids() {
  _impl_.userids_.Clear();
}
inline std::string* PushMsgReq::add_userids() {
  std::string* _s = _internal_add_userids();
  // @@protoc_insertion_point(field_add_mutable:push.PushMsgReq.userIDs)
  return _s;
}
inline const std::string& PushMsgReq::_internal_userids(int index) const {
  return _impl_.userids_.Get(index);
}
inline const std::string& PushMsgReq::userids(int index) const {
  // @@protoc_insertion_point(field_get:push.PushMsgReq.userIDs)
  return _internal_userids(index);
}
inline std::string* PushMsgReq::mutable_userids(int index) {
  // @@protoc_insertion_point(field_mutable:push.PushMsgReq.userIDs)
  return _impl_.userids_.Mutable(index);
}
inline void PushMsgReq::set_userids(int index, const std::string& value) {
  _impl_.userids_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:push.PushMsgReq.userIDs)
}
inline void PushMsgReq::set_userids(int index, std::string&& value) {
  _impl_.userids_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:push.PushMsgReq.userIDs)
}
inline void PushMsgReq::set_userids(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.userids_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:push.PushMsgReq.userIDs)
}
inline void PushMsgReq::set_userids(int index, const char* value, size_t size) {
  _impl_.userids_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:push.PushMsgReq.userIDs)
}
inline std::string* PushMsgReq::_internal_add_userids() {
  return _impl_.userids_.Add();
}
inline void PushMsgReq::add_userids(const std::string& value) {
  _impl_.userids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:push.PushMsgReq.userIDs)
}
inline void PushMsgReq::add_userids(std::string&& value) {
  _impl_.userids_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:push.PushMsgReq.userIDs)
}
inline void PushMsgReq::add_userids(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.userids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:push.PushMsgReq.userIDs)
}
inline void PushMsgReq::add_userids(const char* value, size_t size) {
  _impl_.userids_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:push.PushMsgReq.userIDs)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
PushMsgReq::userids() const {
  // @@protoc_insertion_point(field_list:push.PushMsgReq.userIDs)
  return _impl_.userids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
PushMsgReq::mutable_userids() {
  // @@protoc_insertion_point(field_mutable_list:push.PushMsgReq.userIDs)
  return &_impl_.userids_;
}

// -------------------------------------------------------------------

// PushMsgResp

// -------------------------------------------------------------------

// DelUserPushTokenReq

// string userID = 1;
inline void DelUserPushTokenReq::clear_userid() {
  _impl_.userid_.ClearToEmpty();
}
inline const std::string& DelUserPushTokenReq::userid() const {
  // @@protoc_insertion_point(field_get:push.DelUserPushTokenReq.userID)
  return _internal_userid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DelUserPushTokenReq::set_userid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.userid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:push.DelUserPushTokenReq.userID)
}
inline std::string* DelUserPushTokenReq::mutable_userid() {
  std::string* _s = _internal_mutable_userid();
  // @@protoc_insertion_point(field_mutable:push.DelUserPushTokenReq.userID)
  return _s;
}
inline const std::string& DelUserPushTokenReq::_internal_userid() const {
  return _impl_.userid_.Get();
}
inline void DelUserPushTokenReq::_internal_set_userid(const std::string& value) {
  
  _impl_.userid_.Set(value, GetArenaForAllocation());
}
inline std::string* DelUserPushTokenReq::_internal_mutable_userid() {
  
  return _impl_.userid_.Mutable(GetArenaForAllocation());
}
inline std::string* DelUserPushTokenReq::release_userid() {
  // @@protoc_insertion_point(field_release:push.DelUserPushTokenReq.userID)
  return _impl_.userid_.Release();
}
inline void DelUserPushTokenReq::set_allocated_userid(std::string* userid) {
  if (userid != nullptr) {
    
  } else {
    
  }
  _impl_.userid_.SetAllocated(userid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.userid_.IsDefault()) {
    _impl_.userid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:push.DelUserPushTokenReq.userID)
}

// int32 platformID = 2;
inline void DelUserPushTokenReq::clear_platformid() {
  _impl_.platformid_ = 0;
}
inline int32_t DelUserPushTokenReq::_internal_platformid() const {
  return _impl_.platformid_;
}
inline int32_t DelUserPushTokenReq::platformid() const {
  // @@protoc_insertion_point(field_get:push.DelUserPushTokenReq.platformID)
  return _internal_platformid();
}
inline void DelUserPushTokenReq::_internal_set_platformid(int32_t value) {
  
  _impl_.platformid_ = value;
}
inline void DelUserPushTokenReq::set_platformid(int32_t value) {
  _internal_set_platformid(value);
  // @@protoc_insertion_point(field_set:push.DelUserPushTokenReq.platformID)
}

// -------------------------------------------------------------------

// DelUserPushTokenResp

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace push

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_push_2eproto
