// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gateway_push.proto
// Protobuf C++ Version: 5.29.5

#include "gateway_push.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace gateway_push {

inline constexpr PushToUserResp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PushToUserResp::PushToUserResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PushToUserRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PushToUserRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PushToUserRespDefaultTypeInternal() {}
  union {
    PushToUserResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PushToUserRespDefaultTypeInternal _PushToUserResp_default_instance_;

inline constexpr PushToUserReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : userid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        msgdatabin_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        conversationid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PushToUserReq::PushToUserReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PushToUserReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PushToUserReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PushToUserReqDefaultTypeInternal() {}
  union {
    PushToUserReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PushToUserReqDefaultTypeInternal _PushToUserReq_default_instance_;
}  // namespace gateway_push
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_gateway_5fpush_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_gateway_5fpush_2eproto = nullptr;
const ::uint32_t
    TableStruct_gateway_5fpush_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::gateway_push::PushToUserReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::gateway_push::PushToUserReq, _impl_.userid_),
        PROTOBUF_FIELD_OFFSET(::gateway_push::PushToUserReq, _impl_.msgdatabin_),
        PROTOBUF_FIELD_OFFSET(::gateway_push::PushToUserReq, _impl_.conversationid_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::gateway_push::PushToUserResp, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::gateway_push::PushToUserResp, _impl_.success_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::gateway_push::PushToUserReq)},
        {11, -1, -1, sizeof(::gateway_push::PushToUserResp)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::gateway_push::_PushToUserReq_default_instance_._instance,
    &::gateway_push::_PushToUserResp_default_instance_._instance,
};
const char descriptor_table_protodef_gateway_5fpush_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022gateway_push.proto\022\014gateway_push\"K\n\rPu"
    "shToUserReq\022\016\n\006userID\030\001 \001(\t\022\022\n\nmsgDataBi"
    "n\030\002 \001(\014\022\026\n\016conversationID\030\003 \001(\t\"!\n\016PushT"
    "oUserResp\022\017\n\007success\030\001 \001(\0102]\n\022GatewayPus"
    "hService\022G\n\nPushToUser\022\033.gateway_push.Pu"
    "shToUserReq\032\034.gateway_push.PushToUserRes"
    "pb\006proto3"
};
static ::absl::once_flag descriptor_table_gateway_5fpush_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_gateway_5fpush_2eproto = {
    false,
    false,
    249,
    descriptor_table_protodef_gateway_5fpush_2eproto,
    "gateway_push.proto",
    &descriptor_table_gateway_5fpush_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_gateway_5fpush_2eproto::offsets,
    file_level_enum_descriptors_gateway_5fpush_2eproto,
    file_level_service_descriptors_gateway_5fpush_2eproto,
};
namespace gateway_push {
// ===================================================================

class PushToUserReq::_Internal {
 public:
};

PushToUserReq::PushToUserReq(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gateway_push.PushToUserReq)
}
inline PROTOBUF_NDEBUG_INLINE PushToUserReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::gateway_push::PushToUserReq& from_msg)
      : userid_(arena, from.userid_),
        msgdatabin_(arena, from.msgdatabin_),
        conversationid_(arena, from.conversationid_),
        _cached_size_{0} {}

PushToUserReq::PushToUserReq(
    ::google::protobuf::Arena* arena,
    const PushToUserReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PushToUserReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:gateway_push.PushToUserReq)
}
inline PROTOBUF_NDEBUG_INLINE PushToUserReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : userid_(arena),
        msgdatabin_(arena),
        conversationid_(arena),
        _cached_size_{0} {}

inline void PushToUserReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PushToUserReq::~PushToUserReq() {
  // @@protoc_insertion_point(destructor:gateway_push.PushToUserReq)
  SharedDtor(*this);
}
inline void PushToUserReq::SharedDtor(MessageLite& self) {
  PushToUserReq& this_ = static_cast<PushToUserReq&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.userid_.Destroy();
  this_._impl_.msgdatabin_.Destroy();
  this_._impl_.conversationid_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PushToUserReq::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PushToUserReq(arena);
}
constexpr auto PushToUserReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PushToUserReq),
                                            alignof(PushToUserReq));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PushToUserReq::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PushToUserReq_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PushToUserReq::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PushToUserReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PushToUserReq::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PushToUserReq>(), &PushToUserReq::ByteSizeLong,
            &PushToUserReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PushToUserReq, _impl_._cached_size_),
        false,
    },
    &PushToUserReq::kDescriptorMethods,
    &descriptor_table_gateway_5fpush_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PushToUserReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 55, 2> PushToUserReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::gateway_push::PushToUserReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string userID = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PushToUserReq, _impl_.userid_)}},
    // bytes msgDataBin = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PushToUserReq, _impl_.msgdatabin_)}},
    // string conversationID = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(PushToUserReq, _impl_.conversationid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string userID = 1;
    {PROTOBUF_FIELD_OFFSET(PushToUserReq, _impl_.userid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes msgDataBin = 2;
    {PROTOBUF_FIELD_OFFSET(PushToUserReq, _impl_.msgdatabin_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // string conversationID = 3;
    {PROTOBUF_FIELD_OFFSET(PushToUserReq, _impl_.conversationid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\6\0\16\0\0\0\0"
    "gateway_push.PushToUserReq"
    "userID"
    "conversationID"
  }},
};

PROTOBUF_NOINLINE void PushToUserReq::Clear() {
// @@protoc_insertion_point(message_clear_start:gateway_push.PushToUserReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.userid_.ClearToEmpty();
  _impl_.msgdatabin_.ClearToEmpty();
  _impl_.conversationid_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PushToUserReq::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PushToUserReq& this_ = static_cast<const PushToUserReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PushToUserReq::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PushToUserReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:gateway_push.PushToUserReq)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string userID = 1;
          if (!this_._internal_userid().empty()) {
            const std::string& _s = this_._internal_userid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "gateway_push.PushToUserReq.userID");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // bytes msgDataBin = 2;
          if (!this_._internal_msgdatabin().empty()) {
            const std::string& _s = this_._internal_msgdatabin();
            target = stream->WriteBytesMaybeAliased(2, _s, target);
          }

          // string conversationID = 3;
          if (!this_._internal_conversationid().empty()) {
            const std::string& _s = this_._internal_conversationid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "gateway_push.PushToUserReq.conversationID");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:gateway_push.PushToUserReq)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PushToUserReq::ByteSizeLong(const MessageLite& base) {
          const PushToUserReq& this_ = static_cast<const PushToUserReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PushToUserReq::ByteSizeLong() const {
          const PushToUserReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:gateway_push.PushToUserReq)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string userID = 1;
            if (!this_._internal_userid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_userid());
            }
            // bytes msgDataBin = 2;
            if (!this_._internal_msgdatabin().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_msgdatabin());
            }
            // string conversationID = 3;
            if (!this_._internal_conversationid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_conversationid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PushToUserReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PushToUserReq*>(&to_msg);
  auto& from = static_cast<const PushToUserReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gateway_push.PushToUserReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_userid().empty()) {
    _this->_internal_set_userid(from._internal_userid());
  }
  if (!from._internal_msgdatabin().empty()) {
    _this->_internal_set_msgdatabin(from._internal_msgdatabin());
  }
  if (!from._internal_conversationid().empty()) {
    _this->_internal_set_conversationid(from._internal_conversationid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PushToUserReq::CopyFrom(const PushToUserReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gateway_push.PushToUserReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PushToUserReq::InternalSwap(PushToUserReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.userid_, &other->_impl_.userid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msgdatabin_, &other->_impl_.msgdatabin_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.conversationid_, &other->_impl_.conversationid_, arena);
}

::google::protobuf::Metadata PushToUserReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PushToUserResp::_Internal {
 public:
};

PushToUserResp::PushToUserResp(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gateway_push.PushToUserResp)
}
PushToUserResp::PushToUserResp(
    ::google::protobuf::Arena* arena, const PushToUserResp& from)
    : PushToUserResp(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE PushToUserResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void PushToUserResp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
PushToUserResp::~PushToUserResp() {
  // @@protoc_insertion_point(destructor:gateway_push.PushToUserResp)
  SharedDtor(*this);
}
inline void PushToUserResp::SharedDtor(MessageLite& self) {
  PushToUserResp& this_ = static_cast<PushToUserResp&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PushToUserResp::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PushToUserResp(arena);
}
constexpr auto PushToUserResp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PushToUserResp),
                                            alignof(PushToUserResp));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PushToUserResp::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PushToUserResp_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PushToUserResp::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PushToUserResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PushToUserResp::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PushToUserResp>(), &PushToUserResp::ByteSizeLong,
            &PushToUserResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PushToUserResp, _impl_._cached_size_),
        false,
    },
    &PushToUserResp::kDescriptorMethods,
    &descriptor_table_gateway_5fpush_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PushToUserResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> PushToUserResp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::gateway_push::PushToUserResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PushToUserResp, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PushToUserResp, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(PushToUserResp, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void PushToUserResp::Clear() {
// @@protoc_insertion_point(message_clear_start:gateway_push.PushToUserResp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PushToUserResp::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PushToUserResp& this_ = static_cast<const PushToUserResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PushToUserResp::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PushToUserResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:gateway_push.PushToUserResp)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool success = 1;
          if (this_._internal_success() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_success(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:gateway_push.PushToUserResp)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PushToUserResp::ByteSizeLong(const MessageLite& base) {
          const PushToUserResp& this_ = static_cast<const PushToUserResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PushToUserResp::ByteSizeLong() const {
          const PushToUserResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:gateway_push.PushToUserResp)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bool success = 1;
            if (this_._internal_success() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PushToUserResp::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PushToUserResp*>(&to_msg);
  auto& from = static_cast<const PushToUserResp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gateway_push.PushToUserResp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PushToUserResp::CopyFrom(const PushToUserResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gateway_push.PushToUserResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PushToUserResp::InternalSwap(PushToUserResp* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata PushToUserResp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace gateway_push
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_gateway_5fpush_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
