// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gateway_push.proto

#include "gateway_push.pb.h"
#include "gateway_push.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace gateway_push {

static const char* GatewayPushService_method_names[] = {
  "/gateway_push.GatewayPushService/PushToUser",
};

std::unique_ptr< GatewayPushService::Stub> GatewayPushService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GatewayPushService::Stub> stub(new GatewayPushService::Stub(channel, options));
  return stub;
}

GatewayPushService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_PushToUser_(GatewayPushService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GatewayPushService::Stub::PushToUser(::grpc::ClientContext* context, const ::gateway_push::PushToUserReq& request, ::gateway_push::PushToUserResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gateway_push::PushToUserReq, ::gateway_push::PushToUserResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushToUser_, context, request, response);
}

void GatewayPushService::Stub::async::PushToUser(::grpc::ClientContext* context, const ::gateway_push::PushToUserReq* request, ::gateway_push::PushToUserResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gateway_push::PushToUserReq, ::gateway_push::PushToUserResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushToUser_, context, request, response, std::move(f));
}

void GatewayPushService::Stub::async::PushToUser(::grpc::ClientContext* context, const ::gateway_push::PushToUserReq* request, ::gateway_push::PushToUserResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushToUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gateway_push::PushToUserResp>* GatewayPushService::Stub::PrepareAsyncPushToUserRaw(::grpc::ClientContext* context, const ::gateway_push::PushToUserReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gateway_push::PushToUserResp, ::gateway_push::PushToUserReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushToUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gateway_push::PushToUserResp>* GatewayPushService::Stub::AsyncPushToUserRaw(::grpc::ClientContext* context, const ::gateway_push::PushToUserReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushToUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

GatewayPushService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GatewayPushService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GatewayPushService::Service, ::gateway_push::PushToUserReq, ::gateway_push::PushToUserResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GatewayPushService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gateway_push::PushToUserReq* req,
             ::gateway_push::PushToUserResp* resp) {
               return service->PushToUser(ctx, req, resp);
             }, this)));
}

GatewayPushService::Service::~Service() {
}

::grpc::Status GatewayPushService::Service::PushToUser(::grpc::ServerContext* context, const ::gateway_push::PushToUserReq* request, ::gateway_push::PushToUserResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace gateway_push

