// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

#include "push.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace push {
PROTOBUF_CONSTEXPR PushMsgReq::PushMsgReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.userids_)*/{}
  , /*decltype(_impl_.conversationid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.msgdata_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PushMsgReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PushMsgReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PushMsgReqDefaultTypeInternal() {}
  union {
    PushMsgReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PushMsgReqDefaultTypeInternal _PushMsgReq_default_instance_;
PROTOBUF_CONSTEXPR PushMsgResp::PushMsgResp(
    ::_pbi::ConstantInitialized) {}
struct PushMsgRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PushMsgRespDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PushMsgRespDefaultTypeInternal() {}
  union {
    PushMsgResp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PushMsgRespDefaultTypeInternal _PushMsgResp_default_instance_;
PROTOBUF_CONSTEXPR DelUserPushTokenReq::DelUserPushTokenReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.userid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.platformid_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DelUserPushTokenReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DelUserPushTokenReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DelUserPushTokenReqDefaultTypeInternal() {}
  union {
    DelUserPushTokenReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DelUserPushTokenReqDefaultTypeInternal _DelUserPushTokenReq_default_instance_;
PROTOBUF_CONSTEXPR DelUserPushTokenResp::DelUserPushTokenResp(
    ::_pbi::ConstantInitialized) {}
struct DelUserPushTokenRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DelUserPushTokenRespDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DelUserPushTokenRespDefaultTypeInternal() {}
  union {
    DelUserPushTokenResp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DelUserPushTokenRespDefaultTypeInternal _DelUserPushTokenResp_default_instance_;
}  // namespace push
static ::_pb::Metadata file_level_metadata_push_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_push_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_push_2eproto = nullptr;

const uint32_t TableStruct_push_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::push::PushMsgReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::push::PushMsgReq, _impl_.msgdata_),
  PROTOBUF_FIELD_OFFSET(::push::PushMsgReq, _impl_.conversationid_),
  PROTOBUF_FIELD_OFFSET(::push::PushMsgReq, _impl_.userids_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::push::PushMsgResp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::push::DelUserPushTokenReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::push::DelUserPushTokenReq, _impl_.userid_),
  PROTOBUF_FIELD_OFFSET(::push::DelUserPushTokenReq, _impl_.platformid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::push::DelUserPushTokenResp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::push::PushMsgReq)},
  { 9, -1, -1, sizeof(::push::PushMsgResp)},
  { 15, -1, -1, sizeof(::push::DelUserPushTokenReq)},
  { 23, -1, -1, sizeof(::push::DelUserPushTokenResp)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::push::_PushMsgReq_default_instance_._instance,
  &::push::_PushMsgResp_default_instance_._instance,
  &::push::_DelUserPushTokenReq_default_instance_._instance,
  &::push::_DelUserPushTokenResp_default_instance_._instance,
};

const char descriptor_table_protodef_push_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\npush.proto\022\004push\032\013sdkws.proto\"V\n\nPushM"
  "sgReq\022\037\n\007msgData\030\001 \001(\0132\016.sdkws.MsgData\022\026"
  "\n\016conversationID\030\002 \001(\t\022\017\n\007userIDs\030\003 \003(\t\""
  "\r\n\013PushMsgResp\"9\n\023DelUserPushTokenReq\022\016\n"
  "\006userID\030\001 \001(\t\022\022\n\nplatformID\030\002 \001(\005\"\026\n\024Del"
  "UserPushTokenResp2\210\001\n\013PushService\022.\n\007Pus"
  "hMsg\022\020.push.PushMsgReq\032\021.push.PushMsgRes"
  "p\022I\n\020DelUserPushToken\022\031.push.DelUserPush"
  "TokenReq\032\032.push.DelUserPushTokenRespb\006pr"
  "oto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_push_2eproto_deps[1] = {
  &::descriptor_table_sdkws_2eproto,
};
static ::_pbi::once_flag descriptor_table_push_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_push_2eproto = {
    false, false, 364, descriptor_table_protodef_push_2eproto,
    "push.proto",
    &descriptor_table_push_2eproto_once, descriptor_table_push_2eproto_deps, 1, 4,
    schemas, file_default_instances, TableStruct_push_2eproto::offsets,
    file_level_metadata_push_2eproto, file_level_enum_descriptors_push_2eproto,
    file_level_service_descriptors_push_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_push_2eproto_getter() {
  return &descriptor_table_push_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_push_2eproto(&descriptor_table_push_2eproto);
namespace push {

// ===================================================================

class PushMsgReq::_Internal {
 public:
  static const ::sdkws::MsgData& msgdata(const PushMsgReq* msg);
};

const ::sdkws::MsgData&
PushMsgReq::_Internal::msgdata(const PushMsgReq* msg) {
  return *msg->_impl_.msgdata_;
}
void PushMsgReq::clear_msgdata() {
  if (GetArenaForAllocation() == nullptr && _impl_.msgdata_ != nullptr) {
    delete _impl_.msgdata_;
  }
  _impl_.msgdata_ = nullptr;
}
PushMsgReq::PushMsgReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:push.PushMsgReq)
}
PushMsgReq::PushMsgReq(const PushMsgReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PushMsgReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.userids_){from._impl_.userids_}
    , decltype(_impl_.conversationid_){}
    , decltype(_impl_.msgdata_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.conversationid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.conversationid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_conversationid().empty()) {
    _this->_impl_.conversationid_.Set(from._internal_conversationid(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_msgdata()) {
    _this->_impl_.msgdata_ = new ::sdkws::MsgData(*from._impl_.msgdata_);
  }
  // @@protoc_insertion_point(copy_constructor:push.PushMsgReq)
}

inline void PushMsgReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.userids_){arena}
    , decltype(_impl_.conversationid_){}
    , decltype(_impl_.msgdata_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.conversationid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.conversationid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PushMsgReq::~PushMsgReq() {
  // @@protoc_insertion_point(destructor:push.PushMsgReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PushMsgReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.userids_.~RepeatedPtrField();
  _impl_.conversationid_.Destroy();
  if (this != internal_default_instance()) delete _impl_.msgdata_;
}

void PushMsgReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PushMsgReq::Clear() {
// @@protoc_insertion_point(message_clear_start:push.PushMsgReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.userids_.Clear();
  _impl_.conversationid_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.msgdata_ != nullptr) {
    delete _impl_.msgdata_;
  }
  _impl_.msgdata_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PushMsgReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .sdkws.MsgData msgData = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_msgdata(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string conversationID = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_conversationid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "push.PushMsgReq.conversationID"));
        } else
          goto handle_unusual;
        continue;
      // repeated string userIDs = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_userids();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "push.PushMsgReq.userIDs"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PushMsgReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:push.PushMsgReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .sdkws.MsgData msgData = 1;
  if (this->_internal_has_msgdata()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::msgdata(this),
        _Internal::msgdata(this).GetCachedSize(), target, stream);
  }

  // string conversationID = 2;
  if (!this->_internal_conversationid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_conversationid().data(), static_cast<int>(this->_internal_conversationid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "push.PushMsgReq.conversationID");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_conversationid(), target);
  }

  // repeated string userIDs = 3;
  for (int i = 0, n = this->_internal_userids_size(); i < n; i++) {
    const auto& s = this->_internal_userids(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "push.PushMsgReq.userIDs");
    target = stream->WriteString(3, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:push.PushMsgReq)
  return target;
}

size_t PushMsgReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:push.PushMsgReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string userIDs = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.userids_.size());
  for (int i = 0, n = _impl_.userids_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.userids_.Get(i));
  }

  // string conversationID = 2;
  if (!this->_internal_conversationid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_conversationid());
  }

  // .sdkws.MsgData msgData = 1;
  if (this->_internal_has_msgdata()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.msgdata_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PushMsgReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PushMsgReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PushMsgReq::GetClassData() const { return &_class_data_; }


void PushMsgReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PushMsgReq*>(&to_msg);
  auto& from = static_cast<const PushMsgReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:push.PushMsgReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.userids_.MergeFrom(from._impl_.userids_);
  if (!from._internal_conversationid().empty()) {
    _this->_internal_set_conversationid(from._internal_conversationid());
  }
  if (from._internal_has_msgdata()) {
    _this->_internal_mutable_msgdata()->::sdkws::MsgData::MergeFrom(
        from._internal_msgdata());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PushMsgReq::CopyFrom(const PushMsgReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:push.PushMsgReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PushMsgReq::IsInitialized() const {
  return true;
}

void PushMsgReq::InternalSwap(PushMsgReq* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.userids_.InternalSwap(&other->_impl_.userids_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.conversationid_, lhs_arena,
      &other->_impl_.conversationid_, rhs_arena
  );
  swap(_impl_.msgdata_, other->_impl_.msgdata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PushMsgReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_push_2eproto_getter, &descriptor_table_push_2eproto_once,
      file_level_metadata_push_2eproto[0]);
}

// ===================================================================

class PushMsgResp::_Internal {
 public:
};

PushMsgResp::PushMsgResp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:push.PushMsgResp)
}
PushMsgResp::PushMsgResp(const PushMsgResp& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  PushMsgResp* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:push.PushMsgResp)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PushMsgResp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PushMsgResp::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata PushMsgResp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_push_2eproto_getter, &descriptor_table_push_2eproto_once,
      file_level_metadata_push_2eproto[1]);
}

// ===================================================================

class DelUserPushTokenReq::_Internal {
 public:
};

DelUserPushTokenReq::DelUserPushTokenReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:push.DelUserPushTokenReq)
}
DelUserPushTokenReq::DelUserPushTokenReq(const DelUserPushTokenReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DelUserPushTokenReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.userid_){}
    , decltype(_impl_.platformid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.userid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.userid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_userid().empty()) {
    _this->_impl_.userid_.Set(from._internal_userid(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.platformid_ = from._impl_.platformid_;
  // @@protoc_insertion_point(copy_constructor:push.DelUserPushTokenReq)
}

inline void DelUserPushTokenReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.userid_){}
    , decltype(_impl_.platformid_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.userid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.userid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DelUserPushTokenReq::~DelUserPushTokenReq() {
  // @@protoc_insertion_point(destructor:push.DelUserPushTokenReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DelUserPushTokenReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.userid_.Destroy();
}

void DelUserPushTokenReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DelUserPushTokenReq::Clear() {
// @@protoc_insertion_point(message_clear_start:push.DelUserPushTokenReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.userid_.ClearToEmpty();
  _impl_.platformid_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DelUserPushTokenReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string userID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_userid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "push.DelUserPushTokenReq.userID"));
        } else
          goto handle_unusual;
        continue;
      // int32 platformID = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.platformid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DelUserPushTokenReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:push.DelUserPushTokenReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string userID = 1;
  if (!this->_internal_userid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_userid().data(), static_cast<int>(this->_internal_userid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "push.DelUserPushTokenReq.userID");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_userid(), target);
  }

  // int32 platformID = 2;
  if (this->_internal_platformid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_platformid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:push.DelUserPushTokenReq)
  return target;
}

size_t DelUserPushTokenReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:push.DelUserPushTokenReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string userID = 1;
  if (!this->_internal_userid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_userid());
  }

  // int32 platformID = 2;
  if (this->_internal_platformid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_platformid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DelUserPushTokenReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DelUserPushTokenReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DelUserPushTokenReq::GetClassData() const { return &_class_data_; }


void DelUserPushTokenReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DelUserPushTokenReq*>(&to_msg);
  auto& from = static_cast<const DelUserPushTokenReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:push.DelUserPushTokenReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_userid().empty()) {
    _this->_internal_set_userid(from._internal_userid());
  }
  if (from._internal_platformid() != 0) {
    _this->_internal_set_platformid(from._internal_platformid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DelUserPushTokenReq::CopyFrom(const DelUserPushTokenReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:push.DelUserPushTokenReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DelUserPushTokenReq::IsInitialized() const {
  return true;
}

void DelUserPushTokenReq::InternalSwap(DelUserPushTokenReq* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.userid_, lhs_arena,
      &other->_impl_.userid_, rhs_arena
  );
  swap(_impl_.platformid_, other->_impl_.platformid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DelUserPushTokenReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_push_2eproto_getter, &descriptor_table_push_2eproto_once,
      file_level_metadata_push_2eproto[2]);
}

// ===================================================================

class DelUserPushTokenResp::_Internal {
 public:
};

DelUserPushTokenResp::DelUserPushTokenResp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:push.DelUserPushTokenResp)
}
DelUserPushTokenResp::DelUserPushTokenResp(const DelUserPushTokenResp& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  DelUserPushTokenResp* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:push.DelUserPushTokenResp)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DelUserPushTokenResp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DelUserPushTokenResp::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata DelUserPushTokenResp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_push_2eproto_getter, &descriptor_table_push_2eproto_once,
      file_level_metadata_push_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace push
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::push::PushMsgReq*
Arena::CreateMaybeMessage< ::push::PushMsgReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::push::PushMsgReq >(arena);
}
template<> PROTOBUF_NOINLINE ::push::PushMsgResp*
Arena::CreateMaybeMessage< ::push::PushMsgResp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::push::PushMsgResp >(arena);
}
template<> PROTOBUF_NOINLINE ::push::DelUserPushTokenReq*
Arena::CreateMaybeMessage< ::push::DelUserPushTokenReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::push::DelUserPushTokenReq >(arena);
}
template<> PROTOBUF_NOINLINE ::push::DelUserPushTokenResp*
Arena::CreateMaybeMessage< ::push::DelUserPushTokenResp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::push::DelUserPushTokenResp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
