// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: push.proto
// Protobuf C++ Version: 5.29.5

#include "push.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace push {
              template <typename>
PROTOBUF_CONSTEXPR PushMsgResp::PushMsgResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct PushMsgRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PushMsgRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PushMsgRespDefaultTypeInternal() {}
  union {
    PushMsgResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PushMsgRespDefaultTypeInternal _PushMsgResp_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR DelUserPushTokenResp::DelUserPushTokenResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct DelUserPushTokenRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DelUserPushTokenRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DelUserPushTokenRespDefaultTypeInternal() {}
  union {
    DelUserPushTokenResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DelUserPushTokenRespDefaultTypeInternal _DelUserPushTokenResp_default_instance_;

inline constexpr DelUserPushTokenReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : userid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        platformid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DelUserPushTokenReq::DelUserPushTokenReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DelUserPushTokenReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DelUserPushTokenReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DelUserPushTokenReqDefaultTypeInternal() {}
  union {
    DelUserPushTokenReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DelUserPushTokenReqDefaultTypeInternal _DelUserPushTokenReq_default_instance_;

inline constexpr PushMsgReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        userids_{},
        conversationid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        msgdata_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR PushMsgReq::PushMsgReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PushMsgReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PushMsgReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PushMsgReqDefaultTypeInternal() {}
  union {
    PushMsgReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PushMsgReqDefaultTypeInternal _PushMsgReq_default_instance_;
}  // namespace push
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_push_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_push_2eproto = nullptr;
const ::uint32_t
    TableStruct_push_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::push::PushMsgReq, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::push::PushMsgReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::push::PushMsgReq, _impl_.msgdata_),
        PROTOBUF_FIELD_OFFSET(::push::PushMsgReq, _impl_.conversationid_),
        PROTOBUF_FIELD_OFFSET(::push::PushMsgReq, _impl_.userids_),
        0,
        ~0u,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::push::PushMsgResp, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::push::DelUserPushTokenReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::push::DelUserPushTokenReq, _impl_.userid_),
        PROTOBUF_FIELD_OFFSET(::push::DelUserPushTokenReq, _impl_.platformid_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::push::DelUserPushTokenResp, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::push::PushMsgReq)},
        {14, -1, -1, sizeof(::push::PushMsgResp)},
        {22, -1, -1, sizeof(::push::DelUserPushTokenReq)},
        {32, -1, -1, sizeof(::push::DelUserPushTokenResp)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::push::_PushMsgReq_default_instance_._instance,
    &::push::_PushMsgResp_default_instance_._instance,
    &::push::_DelUserPushTokenReq_default_instance_._instance,
    &::push::_DelUserPushTokenResp_default_instance_._instance,
};
const char descriptor_table_protodef_push_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\npush.proto\022\004push\032\013sdkws.proto\"V\n\nPushM"
    "sgReq\022\037\n\007msgData\030\001 \001(\0132\016.sdkws.MsgData\022\026"
    "\n\016conversationID\030\002 \001(\t\022\017\n\007userIDs\030\003 \003(\t\""
    "\r\n\013PushMsgResp\"9\n\023DelUserPushTokenReq\022\016\n"
    "\006userID\030\001 \001(\t\022\022\n\nplatformID\030\002 \001(\005\"\026\n\024Del"
    "UserPushTokenResp2\210\001\n\013PushService\022.\n\007Pus"
    "hMsg\022\020.push.PushMsgReq\032\021.push.PushMsgRes"
    "p\022I\n\020DelUserPushToken\022\031.push.DelUserPush"
    "TokenReq\032\032.push.DelUserPushTokenRespb\006pr"
    "oto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_push_2eproto_deps[1] =
    {
        &::descriptor_table_sdkws_2eproto,
};
static ::absl::once_flag descriptor_table_push_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_push_2eproto = {
    false,
    false,
    364,
    descriptor_table_protodef_push_2eproto,
    "push.proto",
    &descriptor_table_push_2eproto_once,
    descriptor_table_push_2eproto_deps,
    1,
    4,
    schemas,
    file_default_instances,
    TableStruct_push_2eproto::offsets,
    file_level_enum_descriptors_push_2eproto,
    file_level_service_descriptors_push_2eproto,
};
namespace push {
// ===================================================================

class PushMsgReq::_Internal {
 public:
  using HasBits =
      decltype(std::declval<PushMsgReq>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PushMsgReq, _impl_._has_bits_);
};

void PushMsgReq::clear_msgdata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.msgdata_ != nullptr) _impl_.msgdata_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
PushMsgReq::PushMsgReq(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:push.PushMsgReq)
}
inline PROTOBUF_NDEBUG_INLINE PushMsgReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::push::PushMsgReq& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        userids_{visibility, arena, from.userids_},
        conversationid_(arena, from.conversationid_) {}

PushMsgReq::PushMsgReq(
    ::google::protobuf::Arena* arena,
    const PushMsgReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PushMsgReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.msgdata_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::sdkws::MsgData>(
                              arena, *from._impl_.msgdata_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:push.PushMsgReq)
}
inline PROTOBUF_NDEBUG_INLINE PushMsgReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        userids_{visibility, arena},
        conversationid_(arena) {}

inline void PushMsgReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.msgdata_ = {};
}
PushMsgReq::~PushMsgReq() {
  // @@protoc_insertion_point(destructor:push.PushMsgReq)
  SharedDtor(*this);
}
inline void PushMsgReq::SharedDtor(MessageLite& self) {
  PushMsgReq& this_ = static_cast<PushMsgReq&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.conversationid_.Destroy();
  delete this_._impl_.msgdata_;
  this_._impl_.~Impl_();
}

inline void* PushMsgReq::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PushMsgReq(arena);
}
constexpr auto PushMsgReq::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(PushMsgReq, _impl_.userids_) +
          decltype(PushMsgReq::_impl_.userids_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(PushMsgReq), alignof(PushMsgReq), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&PushMsgReq::PlacementNew_,
                                 sizeof(PushMsgReq),
                                 alignof(PushMsgReq));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PushMsgReq::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PushMsgReq_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PushMsgReq::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PushMsgReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PushMsgReq::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PushMsgReq>(), &PushMsgReq::ByteSizeLong,
            &PushMsgReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PushMsgReq, _impl_._cached_size_),
        false,
    },
    &PushMsgReq::kDescriptorMethods,
    &descriptor_table_push_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PushMsgReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 45, 2> PushMsgReq::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PushMsgReq, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::push::PushMsgReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .sdkws.MsgData msgData = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(PushMsgReq, _impl_.msgdata_)}},
    // string conversationID = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PushMsgReq, _impl_.conversationid_)}},
    // repeated string userIDs = 3;
    {::_pbi::TcParser::FastUR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(PushMsgReq, _impl_.userids_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .sdkws.MsgData msgData = 1;
    {PROTOBUF_FIELD_OFFSET(PushMsgReq, _impl_.msgdata_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string conversationID = 2;
    {PROTOBUF_FIELD_OFFSET(PushMsgReq, _impl_.conversationid_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated string userIDs = 3;
    {PROTOBUF_FIELD_OFFSET(PushMsgReq, _impl_.userids_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::sdkws::MsgData>()},
  }}, {{
    "\17\0\16\7\0\0\0\0"
    "push.PushMsgReq"
    "conversationID"
    "userIDs"
  }},
};

PROTOBUF_NOINLINE void PushMsgReq::Clear() {
// @@protoc_insertion_point(message_clear_start:push.PushMsgReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.userids_.Clear();
  _impl_.conversationid_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.msgdata_ != nullptr);
    _impl_.msgdata_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PushMsgReq::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PushMsgReq& this_ = static_cast<const PushMsgReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PushMsgReq::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PushMsgReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:push.PushMsgReq)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .sdkws.MsgData msgData = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.msgdata_, this_._impl_.msgdata_->GetCachedSize(), target,
                stream);
          }

          // string conversationID = 2;
          if (!this_._internal_conversationid().empty()) {
            const std::string& _s = this_._internal_conversationid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "push.PushMsgReq.conversationID");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // repeated string userIDs = 3;
          for (int i = 0, n = this_._internal_userids_size(); i < n; ++i) {
            const auto& s = this_._internal_userids().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "push.PushMsgReq.userIDs");
            target = stream->WriteString(3, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:push.PushMsgReq)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PushMsgReq::ByteSizeLong(const MessageLite& base) {
          const PushMsgReq& this_ = static_cast<const PushMsgReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PushMsgReq::ByteSizeLong() const {
          const PushMsgReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:push.PushMsgReq)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string userIDs = 3;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_userids().size());
              for (int i = 0, n = this_._internal_userids().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_userids().Get(i));
              }
            }
          }
           {
            // string conversationID = 2;
            if (!this_._internal_conversationid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_conversationid());
            }
          }
           {
            // .sdkws.MsgData msgData = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.msgdata_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PushMsgReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PushMsgReq*>(&to_msg);
  auto& from = static_cast<const PushMsgReq&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:push.PushMsgReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_userids()->MergeFrom(from._internal_userids());
  if (!from._internal_conversationid().empty()) {
    _this->_internal_set_conversationid(from._internal_conversationid());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.msgdata_ != nullptr);
    if (_this->_impl_.msgdata_ == nullptr) {
      _this->_impl_.msgdata_ =
          ::google::protobuf::Message::CopyConstruct<::sdkws::MsgData>(arena, *from._impl_.msgdata_);
    } else {
      _this->_impl_.msgdata_->MergeFrom(*from._impl_.msgdata_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PushMsgReq::CopyFrom(const PushMsgReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:push.PushMsgReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PushMsgReq::InternalSwap(PushMsgReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.userids_.InternalSwap(&other->_impl_.userids_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.conversationid_, &other->_impl_.conversationid_, arena);
  swap(_impl_.msgdata_, other->_impl_.msgdata_);
}

::google::protobuf::Metadata PushMsgReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PushMsgResp::_Internal {
 public:
};

PushMsgResp::PushMsgResp(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:push.PushMsgResp)
}
PushMsgResp::PushMsgResp(
    ::google::protobuf::Arena* arena,
    const PushMsgResp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PushMsgResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:push.PushMsgResp)
}

inline void* PushMsgResp::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PushMsgResp(arena);
}
constexpr auto PushMsgResp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PushMsgResp),
                                            alignof(PushMsgResp));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PushMsgResp::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PushMsgResp_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PushMsgResp::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<PushMsgResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PushMsgResp::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<PushMsgResp>(), &PushMsgResp::ByteSizeLong,
            &PushMsgResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PushMsgResp, _impl_._cached_size_),
        false,
    },
    &PushMsgResp::kDescriptorMethods,
    &descriptor_table_push_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PushMsgResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> PushMsgResp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::push::PushMsgResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata PushMsgResp::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DelUserPushTokenReq::_Internal {
 public:
};

DelUserPushTokenReq::DelUserPushTokenReq(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:push.DelUserPushTokenReq)
}
inline PROTOBUF_NDEBUG_INLINE DelUserPushTokenReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::push::DelUserPushTokenReq& from_msg)
      : userid_(arena, from.userid_),
        _cached_size_{0} {}

DelUserPushTokenReq::DelUserPushTokenReq(
    ::google::protobuf::Arena* arena,
    const DelUserPushTokenReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DelUserPushTokenReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.platformid_ = from._impl_.platformid_;

  // @@protoc_insertion_point(copy_constructor:push.DelUserPushTokenReq)
}
inline PROTOBUF_NDEBUG_INLINE DelUserPushTokenReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : userid_(arena),
        _cached_size_{0} {}

inline void DelUserPushTokenReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.platformid_ = {};
}
DelUserPushTokenReq::~DelUserPushTokenReq() {
  // @@protoc_insertion_point(destructor:push.DelUserPushTokenReq)
  SharedDtor(*this);
}
inline void DelUserPushTokenReq::SharedDtor(MessageLite& self) {
  DelUserPushTokenReq& this_ = static_cast<DelUserPushTokenReq&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.userid_.Destroy();
  this_._impl_.~Impl_();
}

inline void* DelUserPushTokenReq::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DelUserPushTokenReq(arena);
}
constexpr auto DelUserPushTokenReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(DelUserPushTokenReq),
                                            alignof(DelUserPushTokenReq));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DelUserPushTokenReq::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DelUserPushTokenReq_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DelUserPushTokenReq::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<DelUserPushTokenReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DelUserPushTokenReq::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<DelUserPushTokenReq>(), &DelUserPushTokenReq::ByteSizeLong,
            &DelUserPushTokenReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DelUserPushTokenReq, _impl_._cached_size_),
        false,
    },
    &DelUserPushTokenReq::kDescriptorMethods,
    &descriptor_table_push_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DelUserPushTokenReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 39, 2> DelUserPushTokenReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::push::DelUserPushTokenReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 platformID = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DelUserPushTokenReq, _impl_.platformid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(DelUserPushTokenReq, _impl_.platformid_)}},
    // string userID = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(DelUserPushTokenReq, _impl_.userid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string userID = 1;
    {PROTOBUF_FIELD_OFFSET(DelUserPushTokenReq, _impl_.userid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 platformID = 2;
    {PROTOBUF_FIELD_OFFSET(DelUserPushTokenReq, _impl_.platformid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\30\6\0\0\0\0\0\0"
    "push.DelUserPushTokenReq"
    "userID"
  }},
};

PROTOBUF_NOINLINE void DelUserPushTokenReq::Clear() {
// @@protoc_insertion_point(message_clear_start:push.DelUserPushTokenReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.userid_.ClearToEmpty();
  _impl_.platformid_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DelUserPushTokenReq::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DelUserPushTokenReq& this_ = static_cast<const DelUserPushTokenReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DelUserPushTokenReq::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DelUserPushTokenReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:push.DelUserPushTokenReq)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string userID = 1;
          if (!this_._internal_userid().empty()) {
            const std::string& _s = this_._internal_userid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "push.DelUserPushTokenReq.userID");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // int32 platformID = 2;
          if (this_._internal_platformid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_platformid(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:push.DelUserPushTokenReq)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DelUserPushTokenReq::ByteSizeLong(const MessageLite& base) {
          const DelUserPushTokenReq& this_ = static_cast<const DelUserPushTokenReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DelUserPushTokenReq::ByteSizeLong() const {
          const DelUserPushTokenReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:push.DelUserPushTokenReq)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string userID = 1;
            if (!this_._internal_userid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_userid());
            }
            // int32 platformID = 2;
            if (this_._internal_platformid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_platformid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DelUserPushTokenReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DelUserPushTokenReq*>(&to_msg);
  auto& from = static_cast<const DelUserPushTokenReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:push.DelUserPushTokenReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_userid().empty()) {
    _this->_internal_set_userid(from._internal_userid());
  }
  if (from._internal_platformid() != 0) {
    _this->_impl_.platformid_ = from._impl_.platformid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DelUserPushTokenReq::CopyFrom(const DelUserPushTokenReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:push.DelUserPushTokenReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DelUserPushTokenReq::InternalSwap(DelUserPushTokenReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.userid_, &other->_impl_.userid_, arena);
        swap(_impl_.platformid_, other->_impl_.platformid_);
}

::google::protobuf::Metadata DelUserPushTokenReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DelUserPushTokenResp::_Internal {
 public:
};

DelUserPushTokenResp::DelUserPushTokenResp(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:push.DelUserPushTokenResp)
}
DelUserPushTokenResp::DelUserPushTokenResp(
    ::google::protobuf::Arena* arena,
    const DelUserPushTokenResp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DelUserPushTokenResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:push.DelUserPushTokenResp)
}

inline void* DelUserPushTokenResp::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DelUserPushTokenResp(arena);
}
constexpr auto DelUserPushTokenResp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(DelUserPushTokenResp),
                                            alignof(DelUserPushTokenResp));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DelUserPushTokenResp::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DelUserPushTokenResp_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DelUserPushTokenResp::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<DelUserPushTokenResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DelUserPushTokenResp::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<DelUserPushTokenResp>(), &DelUserPushTokenResp::ByteSizeLong,
            &DelUserPushTokenResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DelUserPushTokenResp, _impl_._cached_size_),
        false,
    },
    &DelUserPushTokenResp::kDescriptorMethods,
    &descriptor_table_push_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DelUserPushTokenResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> DelUserPushTokenResp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::push::DelUserPushTokenResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata DelUserPushTokenResp::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace push
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_push_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
