// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: push.proto
// Protobuf C++ Version: 5.29.5

#ifndef push_2eproto_2epb_2eh
#define push_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "sdkws.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_push_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_push_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_push_2eproto;
namespace push {
class AckMsgReq;
struct AckMsgReqDefaultTypeInternal;
extern AckMsgReqDefaultTypeInternal _AckMsgReq_default_instance_;
class AckMsgResp;
struct AckMsgRespDefaultTypeInternal;
extern AckMsgRespDefaultTypeInternal _AckMsgResp_default_instance_;
class AddPendingOfflineAckReq;
struct AddPendingOfflineAckReqDefaultTypeInternal;
extern AddPendingOfflineAckReqDefaultTypeInternal _AddPendingOfflineAckReq_default_instance_;
class AddPendingOfflineAckResp;
struct AddPendingOfflineAckRespDefaultTypeInternal;
extern AddPendingOfflineAckRespDefaultTypeInternal _AddPendingOfflineAckResp_default_instance_;
class DelUserPushTokenReq;
struct DelUserPushTokenReqDefaultTypeInternal;
extern DelUserPushTokenReqDefaultTypeInternal _DelUserPushTokenReq_default_instance_;
class DelUserPushTokenResp;
struct DelUserPushTokenRespDefaultTypeInternal;
extern DelUserPushTokenRespDefaultTypeInternal _DelUserPushTokenResp_default_instance_;
class PushMsgReq;
struct PushMsgReqDefaultTypeInternal;
extern PushMsgReqDefaultTypeInternal _PushMsgReq_default_instance_;
class PushMsgResp;
struct PushMsgRespDefaultTypeInternal;
extern PushMsgRespDefaultTypeInternal _PushMsgResp_default_instance_;
}  // namespace push
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace push {

// ===================================================================


// -------------------------------------------------------------------

class PushMsgResp final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:push.PushMsgResp) */ {
 public:
  inline PushMsgResp() : PushMsgResp(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PushMsgResp* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PushMsgResp));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PushMsgResp(
      ::google::protobuf::internal::ConstantInitialized);

  inline PushMsgResp(const PushMsgResp& from) : PushMsgResp(nullptr, from) {}
  inline PushMsgResp(PushMsgResp&& from) noexcept
      : PushMsgResp(nullptr, std::move(from)) {}
  inline PushMsgResp& operator=(const PushMsgResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline PushMsgResp& operator=(PushMsgResp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PushMsgResp& default_instance() {
    return *internal_default_instance();
  }
  static inline const PushMsgResp* internal_default_instance() {
    return reinterpret_cast<const PushMsgResp*>(
        &_PushMsgResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PushMsgResp& a, PushMsgResp& b) { a.Swap(&b); }
  inline void Swap(PushMsgResp* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PushMsgResp* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PushMsgResp* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<PushMsgResp>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const PushMsgResp& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const PushMsgResp& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "push.PushMsgResp"; }

 protected:
  explicit PushMsgResp(::google::protobuf::Arena* arena);
  PushMsgResp(::google::protobuf::Arena* arena, const PushMsgResp& from);
  PushMsgResp(::google::protobuf::Arena* arena, PushMsgResp&& from) noexcept
      : PushMsgResp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:push.PushMsgResp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PushMsgResp& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_push_2eproto;
};
// -------------------------------------------------------------------

class DelUserPushTokenResp final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:push.DelUserPushTokenResp) */ {
 public:
  inline DelUserPushTokenResp() : DelUserPushTokenResp(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DelUserPushTokenResp* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DelUserPushTokenResp));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DelUserPushTokenResp(
      ::google::protobuf::internal::ConstantInitialized);

  inline DelUserPushTokenResp(const DelUserPushTokenResp& from) : DelUserPushTokenResp(nullptr, from) {}
  inline DelUserPushTokenResp(DelUserPushTokenResp&& from) noexcept
      : DelUserPushTokenResp(nullptr, std::move(from)) {}
  inline DelUserPushTokenResp& operator=(const DelUserPushTokenResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline DelUserPushTokenResp& operator=(DelUserPushTokenResp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DelUserPushTokenResp& default_instance() {
    return *internal_default_instance();
  }
  static inline const DelUserPushTokenResp* internal_default_instance() {
    return reinterpret_cast<const DelUserPushTokenResp*>(
        &_DelUserPushTokenResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(DelUserPushTokenResp& a, DelUserPushTokenResp& b) { a.Swap(&b); }
  inline void Swap(DelUserPushTokenResp* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DelUserPushTokenResp* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DelUserPushTokenResp* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<DelUserPushTokenResp>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const DelUserPushTokenResp& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const DelUserPushTokenResp& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "push.DelUserPushTokenResp"; }

 protected:
  explicit DelUserPushTokenResp(::google::protobuf::Arena* arena);
  DelUserPushTokenResp(::google::protobuf::Arena* arena, const DelUserPushTokenResp& from);
  DelUserPushTokenResp(::google::protobuf::Arena* arena, DelUserPushTokenResp&& from) noexcept
      : DelUserPushTokenResp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:push.DelUserPushTokenResp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DelUserPushTokenResp& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_push_2eproto;
};
// -------------------------------------------------------------------

class DelUserPushTokenReq final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:push.DelUserPushTokenReq) */ {
 public:
  inline DelUserPushTokenReq() : DelUserPushTokenReq(nullptr) {}
  ~DelUserPushTokenReq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DelUserPushTokenReq* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DelUserPushTokenReq));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DelUserPushTokenReq(
      ::google::protobuf::internal::ConstantInitialized);

  inline DelUserPushTokenReq(const DelUserPushTokenReq& from) : DelUserPushTokenReq(nullptr, from) {}
  inline DelUserPushTokenReq(DelUserPushTokenReq&& from) noexcept
      : DelUserPushTokenReq(nullptr, std::move(from)) {}
  inline DelUserPushTokenReq& operator=(const DelUserPushTokenReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline DelUserPushTokenReq& operator=(DelUserPushTokenReq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DelUserPushTokenReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const DelUserPushTokenReq* internal_default_instance() {
    return reinterpret_cast<const DelUserPushTokenReq*>(
        &_DelUserPushTokenReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(DelUserPushTokenReq& a, DelUserPushTokenReq& b) { a.Swap(&b); }
  inline void Swap(DelUserPushTokenReq* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DelUserPushTokenReq* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DelUserPushTokenReq* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DelUserPushTokenReq>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DelUserPushTokenReq& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DelUserPushTokenReq& from) { DelUserPushTokenReq::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DelUserPushTokenReq* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "push.DelUserPushTokenReq"; }

 protected:
  explicit DelUserPushTokenReq(::google::protobuf::Arena* arena);
  DelUserPushTokenReq(::google::protobuf::Arena* arena, const DelUserPushTokenReq& from);
  DelUserPushTokenReq(::google::protobuf::Arena* arena, DelUserPushTokenReq&& from) noexcept
      : DelUserPushTokenReq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserIDFieldNumber = 1,
    kPlatformIDFieldNumber = 2,
  };
  // string userID = 1;
  void clear_userid() ;
  const std::string& userid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_userid(Arg_&& arg, Args_... args);
  std::string* mutable_userid();
  PROTOBUF_NODISCARD std::string* release_userid();
  void set_allocated_userid(std::string* value);

  private:
  const std::string& _internal_userid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_userid(
      const std::string& value);
  std::string* _internal_mutable_userid();

  public:
  // int32 platformID = 2;
  void clear_platformid() ;
  ::int32_t platformid() const;
  void set_platformid(::int32_t value);

  private:
  ::int32_t _internal_platformid() const;
  void _internal_set_platformid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:push.DelUserPushTokenReq)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      39, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DelUserPushTokenReq& from_msg);
    ::google::protobuf::internal::ArenaStringPtr userid_;
    ::int32_t platformid_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_push_2eproto;
};
// -------------------------------------------------------------------

class AddPendingOfflineAckResp final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:push.AddPendingOfflineAckResp) */ {
 public:
  inline AddPendingOfflineAckResp() : AddPendingOfflineAckResp(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AddPendingOfflineAckResp* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AddPendingOfflineAckResp));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AddPendingOfflineAckResp(
      ::google::protobuf::internal::ConstantInitialized);

  inline AddPendingOfflineAckResp(const AddPendingOfflineAckResp& from) : AddPendingOfflineAckResp(nullptr, from) {}
  inline AddPendingOfflineAckResp(AddPendingOfflineAckResp&& from) noexcept
      : AddPendingOfflineAckResp(nullptr, std::move(from)) {}
  inline AddPendingOfflineAckResp& operator=(const AddPendingOfflineAckResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddPendingOfflineAckResp& operator=(AddPendingOfflineAckResp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddPendingOfflineAckResp& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddPendingOfflineAckResp* internal_default_instance() {
    return reinterpret_cast<const AddPendingOfflineAckResp*>(
        &_AddPendingOfflineAckResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 7;
  friend void swap(AddPendingOfflineAckResp& a, AddPendingOfflineAckResp& b) { a.Swap(&b); }
  inline void Swap(AddPendingOfflineAckResp* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddPendingOfflineAckResp* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddPendingOfflineAckResp* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<AddPendingOfflineAckResp>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const AddPendingOfflineAckResp& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const AddPendingOfflineAckResp& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "push.AddPendingOfflineAckResp"; }

 protected:
  explicit AddPendingOfflineAckResp(::google::protobuf::Arena* arena);
  AddPendingOfflineAckResp(::google::protobuf::Arena* arena, const AddPendingOfflineAckResp& from);
  AddPendingOfflineAckResp(::google::protobuf::Arena* arena, AddPendingOfflineAckResp&& from) noexcept
      : AddPendingOfflineAckResp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:push.AddPendingOfflineAckResp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AddPendingOfflineAckResp& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_push_2eproto;
};
// -------------------------------------------------------------------

class AddPendingOfflineAckReq final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:push.AddPendingOfflineAckReq) */ {
 public:
  inline AddPendingOfflineAckReq() : AddPendingOfflineAckReq(nullptr) {}
  ~AddPendingOfflineAckReq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AddPendingOfflineAckReq* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AddPendingOfflineAckReq));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AddPendingOfflineAckReq(
      ::google::protobuf::internal::ConstantInitialized);

  inline AddPendingOfflineAckReq(const AddPendingOfflineAckReq& from) : AddPendingOfflineAckReq(nullptr, from) {}
  inline AddPendingOfflineAckReq(AddPendingOfflineAckReq&& from) noexcept
      : AddPendingOfflineAckReq(nullptr, std::move(from)) {}
  inline AddPendingOfflineAckReq& operator=(const AddPendingOfflineAckReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddPendingOfflineAckReq& operator=(AddPendingOfflineAckReq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddPendingOfflineAckReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddPendingOfflineAckReq* internal_default_instance() {
    return reinterpret_cast<const AddPendingOfflineAckReq*>(
        &_AddPendingOfflineAckReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(AddPendingOfflineAckReq& a, AddPendingOfflineAckReq& b) { a.Swap(&b); }
  inline void Swap(AddPendingOfflineAckReq* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddPendingOfflineAckReq* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddPendingOfflineAckReq* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AddPendingOfflineAckReq>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AddPendingOfflineAckReq& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AddPendingOfflineAckReq& from) { AddPendingOfflineAckReq::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AddPendingOfflineAckReq* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "push.AddPendingOfflineAckReq"; }

 protected:
  explicit AddPendingOfflineAckReq(::google::protobuf::Arena* arena);
  AddPendingOfflineAckReq(::google::protobuf::Arena* arena, const AddPendingOfflineAckReq& from);
  AddPendingOfflineAckReq(::google::protobuf::Arena* arena, AddPendingOfflineAckReq&& from) noexcept
      : AddPendingOfflineAckReq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserIDFieldNumber = 1,
    kServerMsgIDFieldNumber = 2,
    kSeqFieldNumber = 3,
  };
  // string userID = 1;
  void clear_userid() ;
  const std::string& userid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_userid(Arg_&& arg, Args_... args);
  std::string* mutable_userid();
  PROTOBUF_NODISCARD std::string* release_userid();
  void set_allocated_userid(std::string* value);

  private:
  const std::string& _internal_userid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_userid(
      const std::string& value);
  std::string* _internal_mutable_userid();

  public:
  // string serverMsgID = 2;
  void clear_servermsgid() ;
  const std::string& servermsgid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_servermsgid(Arg_&& arg, Args_... args);
  std::string* mutable_servermsgid();
  PROTOBUF_NODISCARD std::string* release_servermsgid();
  void set_allocated_servermsgid(std::string* value);

  private:
  const std::string& _internal_servermsgid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_servermsgid(
      const std::string& value);
  std::string* _internal_mutable_servermsgid();

  public:
  // int64 seq = 3;
  void clear_seq() ;
  ::int64_t seq() const;
  void set_seq(::int64_t value);

  private:
  ::int64_t _internal_seq() const;
  void _internal_set_seq(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:push.AddPendingOfflineAckReq)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      54, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AddPendingOfflineAckReq& from_msg);
    ::google::protobuf::internal::ArenaStringPtr userid_;
    ::google::protobuf::internal::ArenaStringPtr servermsgid_;
    ::int64_t seq_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_push_2eproto;
};
// -------------------------------------------------------------------

class AckMsgResp final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:push.AckMsgResp) */ {
 public:
  inline AckMsgResp() : AckMsgResp(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AckMsgResp* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AckMsgResp));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AckMsgResp(
      ::google::protobuf::internal::ConstantInitialized);

  inline AckMsgResp(const AckMsgResp& from) : AckMsgResp(nullptr, from) {}
  inline AckMsgResp(AckMsgResp&& from) noexcept
      : AckMsgResp(nullptr, std::move(from)) {}
  inline AckMsgResp& operator=(const AckMsgResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline AckMsgResp& operator=(AckMsgResp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AckMsgResp& default_instance() {
    return *internal_default_instance();
  }
  static inline const AckMsgResp* internal_default_instance() {
    return reinterpret_cast<const AckMsgResp*>(
        &_AckMsgResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(AckMsgResp& a, AckMsgResp& b) { a.Swap(&b); }
  inline void Swap(AckMsgResp* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AckMsgResp* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AckMsgResp* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<AckMsgResp>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const AckMsgResp& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const AckMsgResp& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "push.AckMsgResp"; }

 protected:
  explicit AckMsgResp(::google::protobuf::Arena* arena);
  AckMsgResp(::google::protobuf::Arena* arena, const AckMsgResp& from);
  AckMsgResp(::google::protobuf::Arena* arena, AckMsgResp&& from) noexcept
      : AckMsgResp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:push.AckMsgResp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AckMsgResp& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_push_2eproto;
};
// -------------------------------------------------------------------

class AckMsgReq final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:push.AckMsgReq) */ {
 public:
  inline AckMsgReq() : AckMsgReq(nullptr) {}
  ~AckMsgReq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AckMsgReq* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AckMsgReq));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AckMsgReq(
      ::google::protobuf::internal::ConstantInitialized);

  inline AckMsgReq(const AckMsgReq& from) : AckMsgReq(nullptr, from) {}
  inline AckMsgReq(AckMsgReq&& from) noexcept
      : AckMsgReq(nullptr, std::move(from)) {}
  inline AckMsgReq& operator=(const AckMsgReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline AckMsgReq& operator=(AckMsgReq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AckMsgReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const AckMsgReq* internal_default_instance() {
    return reinterpret_cast<const AckMsgReq*>(
        &_AckMsgReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(AckMsgReq& a, AckMsgReq& b) { a.Swap(&b); }
  inline void Swap(AckMsgReq* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AckMsgReq* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AckMsgReq* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AckMsgReq>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AckMsgReq& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AckMsgReq& from) { AckMsgReq::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AckMsgReq* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "push.AckMsgReq"; }

 protected:
  explicit AckMsgReq(::google::protobuf::Arena* arena);
  AckMsgReq(::google::protobuf::Arena* arena, const AckMsgReq& from);
  AckMsgReq(::google::protobuf::Arena* arena, AckMsgReq&& from) noexcept
      : AckMsgReq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserIDFieldNumber = 1,
    kServerMsgIDFieldNumber = 2,
    kSeqFieldNumber = 3,
    kAckTypeFieldNumber = 4,
  };
  // string userID = 1;
  void clear_userid() ;
  const std::string& userid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_userid(Arg_&& arg, Args_... args);
  std::string* mutable_userid();
  PROTOBUF_NODISCARD std::string* release_userid();
  void set_allocated_userid(std::string* value);

  private:
  const std::string& _internal_userid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_userid(
      const std::string& value);
  std::string* _internal_mutable_userid();

  public:
  // string serverMsgID = 2;
  void clear_servermsgid() ;
  const std::string& servermsgid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_servermsgid(Arg_&& arg, Args_... args);
  std::string* mutable_servermsgid();
  PROTOBUF_NODISCARD std::string* release_servermsgid();
  void set_allocated_servermsgid(std::string* value);

  private:
  const std::string& _internal_servermsgid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_servermsgid(
      const std::string& value);
  std::string* _internal_mutable_servermsgid();

  public:
  // int64 seq = 3;
  void clear_seq() ;
  ::int64_t seq() const;
  void set_seq(::int64_t value);

  private:
  ::int64_t _internal_seq() const;
  void _internal_set_seq(::int64_t value);

  public:
  // int32 ackType = 4;
  void clear_acktype() ;
  ::int32_t acktype() const;
  void set_acktype(::int32_t value);

  private:
  ::int32_t _internal_acktype() const;
  void _internal_set_acktype(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:push.AckMsgReq)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      40, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AckMsgReq& from_msg);
    ::google::protobuf::internal::ArenaStringPtr userid_;
    ::google::protobuf::internal::ArenaStringPtr servermsgid_;
    ::int64_t seq_;
    ::int32_t acktype_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_push_2eproto;
};
// -------------------------------------------------------------------

class PushMsgReq final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:push.PushMsgReq) */ {
 public:
  inline PushMsgReq() : PushMsgReq(nullptr) {}
  ~PushMsgReq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PushMsgReq* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PushMsgReq));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PushMsgReq(
      ::google::protobuf::internal::ConstantInitialized);

  inline PushMsgReq(const PushMsgReq& from) : PushMsgReq(nullptr, from) {}
  inline PushMsgReq(PushMsgReq&& from) noexcept
      : PushMsgReq(nullptr, std::move(from)) {}
  inline PushMsgReq& operator=(const PushMsgReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline PushMsgReq& operator=(PushMsgReq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PushMsgReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const PushMsgReq* internal_default_instance() {
    return reinterpret_cast<const PushMsgReq*>(
        &_PushMsgReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PushMsgReq& a, PushMsgReq& b) { a.Swap(&b); }
  inline void Swap(PushMsgReq* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PushMsgReq* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PushMsgReq* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PushMsgReq>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PushMsgReq& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PushMsgReq& from) { PushMsgReq::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PushMsgReq* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "push.PushMsgReq"; }

 protected:
  explicit PushMsgReq(::google::protobuf::Arena* arena);
  PushMsgReq(::google::protobuf::Arena* arena, const PushMsgReq& from);
  PushMsgReq(::google::protobuf::Arena* arena, PushMsgReq&& from) noexcept
      : PushMsgReq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserIDsFieldNumber = 3,
    kConversationIDFieldNumber = 2,
    kMsgDataFieldNumber = 1,
  };
  // repeated string userIDs = 3;
  int userids_size() const;
  private:
  int _internal_userids_size() const;

  public:
  void clear_userids() ;
  const std::string& userids(int index) const;
  std::string* mutable_userids(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_userids(int index, Arg_&& value, Args_... args);
  std::string* add_userids();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_userids(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& userids() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_userids();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_userids() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_userids();

  public:
  // string conversationID = 2;
  void clear_conversationid() ;
  const std::string& conversationid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_conversationid(Arg_&& arg, Args_... args);
  std::string* mutable_conversationid();
  PROTOBUF_NODISCARD std::string* release_conversationid();
  void set_allocated_conversationid(std::string* value);

  private:
  const std::string& _internal_conversationid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_conversationid(
      const std::string& value);
  std::string* _internal_mutable_conversationid();

  public:
  // .sdkws.MsgData msgData = 1;
  bool has_msgdata() const;
  void clear_msgdata() ;
  const ::sdkws::MsgData& msgdata() const;
  PROTOBUF_NODISCARD ::sdkws::MsgData* release_msgdata();
  ::sdkws::MsgData* mutable_msgdata();
  void set_allocated_msgdata(::sdkws::MsgData* value);
  void unsafe_arena_set_allocated_msgdata(::sdkws::MsgData* value);
  ::sdkws::MsgData* unsafe_arena_release_msgdata();

  private:
  const ::sdkws::MsgData& _internal_msgdata() const;
  ::sdkws::MsgData* _internal_mutable_msgdata();

  public:
  // @@protoc_insertion_point(class_scope:push.PushMsgReq)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      45, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PushMsgReq& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<std::string> userids_;
    ::google::protobuf::internal::ArenaStringPtr conversationid_;
    ::sdkws::MsgData* msgdata_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_push_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PushMsgReq

// .sdkws.MsgData msgData = 1;
inline bool PushMsgReq::has_msgdata() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.msgdata_ != nullptr);
  return value;
}
inline const ::sdkws::MsgData& PushMsgReq::_internal_msgdata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::sdkws::MsgData* p = _impl_.msgdata_;
  return p != nullptr ? *p : reinterpret_cast<const ::sdkws::MsgData&>(::sdkws::_MsgData_default_instance_);
}
inline const ::sdkws::MsgData& PushMsgReq::msgdata() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:push.PushMsgReq.msgData)
  return _internal_msgdata();
}
inline void PushMsgReq::unsafe_arena_set_allocated_msgdata(::sdkws::MsgData* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.msgdata_);
  }
  _impl_.msgdata_ = reinterpret_cast<::sdkws::MsgData*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:push.PushMsgReq.msgData)
}
inline ::sdkws::MsgData* PushMsgReq::release_msgdata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::sdkws::MsgData* released = _impl_.msgdata_;
  _impl_.msgdata_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::sdkws::MsgData* PushMsgReq::unsafe_arena_release_msgdata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:push.PushMsgReq.msgData)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::sdkws::MsgData* temp = _impl_.msgdata_;
  _impl_.msgdata_ = nullptr;
  return temp;
}
inline ::sdkws::MsgData* PushMsgReq::_internal_mutable_msgdata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.msgdata_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::sdkws::MsgData>(GetArena());
    _impl_.msgdata_ = reinterpret_cast<::sdkws::MsgData*>(p);
  }
  return _impl_.msgdata_;
}
inline ::sdkws::MsgData* PushMsgReq::mutable_msgdata() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::sdkws::MsgData* _msg = _internal_mutable_msgdata();
  // @@protoc_insertion_point(field_mutable:push.PushMsgReq.msgData)
  return _msg;
}
inline void PushMsgReq::set_allocated_msgdata(::sdkws::MsgData* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.msgdata_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.msgdata_ = reinterpret_cast<::sdkws::MsgData*>(value);
  // @@protoc_insertion_point(field_set_allocated:push.PushMsgReq.msgData)
}

// string conversationID = 2;
inline void PushMsgReq::clear_conversationid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.conversationid_.ClearToEmpty();
}
inline const std::string& PushMsgReq::conversationid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:push.PushMsgReq.conversationID)
  return _internal_conversationid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void PushMsgReq::set_conversationid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.conversationid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:push.PushMsgReq.conversationID)
}
inline std::string* PushMsgReq::mutable_conversationid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_conversationid();
  // @@protoc_insertion_point(field_mutable:push.PushMsgReq.conversationID)
  return _s;
}
inline const std::string& PushMsgReq::_internal_conversationid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.conversationid_.Get();
}
inline void PushMsgReq::_internal_set_conversationid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.conversationid_.Set(value, GetArena());
}
inline std::string* PushMsgReq::_internal_mutable_conversationid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.conversationid_.Mutable( GetArena());
}
inline std::string* PushMsgReq::release_conversationid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:push.PushMsgReq.conversationID)
  return _impl_.conversationid_.Release();
}
inline void PushMsgReq::set_allocated_conversationid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.conversationid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.conversationid_.IsDefault()) {
    _impl_.conversationid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:push.PushMsgReq.conversationID)
}

// repeated string userIDs = 3;
inline int PushMsgReq::_internal_userids_size() const {
  return _internal_userids().size();
}
inline int PushMsgReq::userids_size() const {
  return _internal_userids_size();
}
inline void PushMsgReq::clear_userids() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userids_.Clear();
}
inline std::string* PushMsgReq::add_userids() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_userids()->Add();
  // @@protoc_insertion_point(field_add_mutable:push.PushMsgReq.userIDs)
  return _s;
}
inline const std::string& PushMsgReq::userids(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:push.PushMsgReq.userIDs)
  return _internal_userids().Get(index);
}
inline std::string* PushMsgReq::mutable_userids(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:push.PushMsgReq.userIDs)
  return _internal_mutable_userids()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void PushMsgReq::set_userids(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_userids()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:push.PushMsgReq.userIDs)
}
template <typename Arg_, typename... Args_>
inline void PushMsgReq::add_userids(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_userids(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:push.PushMsgReq.userIDs)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
PushMsgReq::userids() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:push.PushMsgReq.userIDs)
  return _internal_userids();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
PushMsgReq::mutable_userids() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:push.PushMsgReq.userIDs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_userids();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
PushMsgReq::_internal_userids() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.userids_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
PushMsgReq::_internal_mutable_userids() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.userids_;
}

// -------------------------------------------------------------------

// PushMsgResp

// -------------------------------------------------------------------

// DelUserPushTokenReq

// string userID = 1;
inline void DelUserPushTokenReq::clear_userid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userid_.ClearToEmpty();
}
inline const std::string& DelUserPushTokenReq::userid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:push.DelUserPushTokenReq.userID)
  return _internal_userid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DelUserPushTokenReq::set_userid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:push.DelUserPushTokenReq.userID)
}
inline std::string* DelUserPushTokenReq::mutable_userid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_userid();
  // @@protoc_insertion_point(field_mutable:push.DelUserPushTokenReq.userID)
  return _s;
}
inline const std::string& DelUserPushTokenReq::_internal_userid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.userid_.Get();
}
inline void DelUserPushTokenReq::_internal_set_userid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userid_.Set(value, GetArena());
}
inline std::string* DelUserPushTokenReq::_internal_mutable_userid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.userid_.Mutable( GetArena());
}
inline std::string* DelUserPushTokenReq::release_userid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:push.DelUserPushTokenReq.userID)
  return _impl_.userid_.Release();
}
inline void DelUserPushTokenReq::set_allocated_userid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.userid_.IsDefault()) {
    _impl_.userid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:push.DelUserPushTokenReq.userID)
}

// int32 platformID = 2;
inline void DelUserPushTokenReq::clear_platformid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.platformid_ = 0;
}
inline ::int32_t DelUserPushTokenReq::platformid() const {
  // @@protoc_insertion_point(field_get:push.DelUserPushTokenReq.platformID)
  return _internal_platformid();
}
inline void DelUserPushTokenReq::set_platformid(::int32_t value) {
  _internal_set_platformid(value);
  // @@protoc_insertion_point(field_set:push.DelUserPushTokenReq.platformID)
}
inline ::int32_t DelUserPushTokenReq::_internal_platformid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.platformid_;
}
inline void DelUserPushTokenReq::_internal_set_platformid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.platformid_ = value;
}

// -------------------------------------------------------------------

// DelUserPushTokenResp

// -------------------------------------------------------------------

// AckMsgReq

// string userID = 1;
inline void AckMsgReq::clear_userid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userid_.ClearToEmpty();
}
inline const std::string& AckMsgReq::userid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:push.AckMsgReq.userID)
  return _internal_userid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AckMsgReq::set_userid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:push.AckMsgReq.userID)
}
inline std::string* AckMsgReq::mutable_userid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_userid();
  // @@protoc_insertion_point(field_mutable:push.AckMsgReq.userID)
  return _s;
}
inline const std::string& AckMsgReq::_internal_userid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.userid_.Get();
}
inline void AckMsgReq::_internal_set_userid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userid_.Set(value, GetArena());
}
inline std::string* AckMsgReq::_internal_mutable_userid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.userid_.Mutable( GetArena());
}
inline std::string* AckMsgReq::release_userid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:push.AckMsgReq.userID)
  return _impl_.userid_.Release();
}
inline void AckMsgReq::set_allocated_userid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.userid_.IsDefault()) {
    _impl_.userid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:push.AckMsgReq.userID)
}

// string serverMsgID = 2;
inline void AckMsgReq::clear_servermsgid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.servermsgid_.ClearToEmpty();
}
inline const std::string& AckMsgReq::servermsgid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:push.AckMsgReq.serverMsgID)
  return _internal_servermsgid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AckMsgReq::set_servermsgid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.servermsgid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:push.AckMsgReq.serverMsgID)
}
inline std::string* AckMsgReq::mutable_servermsgid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_servermsgid();
  // @@protoc_insertion_point(field_mutable:push.AckMsgReq.serverMsgID)
  return _s;
}
inline const std::string& AckMsgReq::_internal_servermsgid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.servermsgid_.Get();
}
inline void AckMsgReq::_internal_set_servermsgid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.servermsgid_.Set(value, GetArena());
}
inline std::string* AckMsgReq::_internal_mutable_servermsgid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.servermsgid_.Mutable( GetArena());
}
inline std::string* AckMsgReq::release_servermsgid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:push.AckMsgReq.serverMsgID)
  return _impl_.servermsgid_.Release();
}
inline void AckMsgReq::set_allocated_servermsgid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.servermsgid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.servermsgid_.IsDefault()) {
    _impl_.servermsgid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:push.AckMsgReq.serverMsgID)
}

// int64 seq = 3;
inline void AckMsgReq::clear_seq() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seq_ = ::int64_t{0};
}
inline ::int64_t AckMsgReq::seq() const {
  // @@protoc_insertion_point(field_get:push.AckMsgReq.seq)
  return _internal_seq();
}
inline void AckMsgReq::set_seq(::int64_t value) {
  _internal_set_seq(value);
  // @@protoc_insertion_point(field_set:push.AckMsgReq.seq)
}
inline ::int64_t AckMsgReq::_internal_seq() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.seq_;
}
inline void AckMsgReq::_internal_set_seq(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seq_ = value;
}

// int32 ackType = 4;
inline void AckMsgReq::clear_acktype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.acktype_ = 0;
}
inline ::int32_t AckMsgReq::acktype() const {
  // @@protoc_insertion_point(field_get:push.AckMsgReq.ackType)
  return _internal_acktype();
}
inline void AckMsgReq::set_acktype(::int32_t value) {
  _internal_set_acktype(value);
  // @@protoc_insertion_point(field_set:push.AckMsgReq.ackType)
}
inline ::int32_t AckMsgReq::_internal_acktype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.acktype_;
}
inline void AckMsgReq::_internal_set_acktype(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.acktype_ = value;
}

// -------------------------------------------------------------------

// AckMsgResp

// -------------------------------------------------------------------

// AddPendingOfflineAckReq

// string userID = 1;
inline void AddPendingOfflineAckReq::clear_userid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userid_.ClearToEmpty();
}
inline const std::string& AddPendingOfflineAckReq::userid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:push.AddPendingOfflineAckReq.userID)
  return _internal_userid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AddPendingOfflineAckReq::set_userid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:push.AddPendingOfflineAckReq.userID)
}
inline std::string* AddPendingOfflineAckReq::mutable_userid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_userid();
  // @@protoc_insertion_point(field_mutable:push.AddPendingOfflineAckReq.userID)
  return _s;
}
inline const std::string& AddPendingOfflineAckReq::_internal_userid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.userid_.Get();
}
inline void AddPendingOfflineAckReq::_internal_set_userid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userid_.Set(value, GetArena());
}
inline std::string* AddPendingOfflineAckReq::_internal_mutable_userid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.userid_.Mutable( GetArena());
}
inline std::string* AddPendingOfflineAckReq::release_userid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:push.AddPendingOfflineAckReq.userID)
  return _impl_.userid_.Release();
}
inline void AddPendingOfflineAckReq::set_allocated_userid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.userid_.IsDefault()) {
    _impl_.userid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:push.AddPendingOfflineAckReq.userID)
}

// string serverMsgID = 2;
inline void AddPendingOfflineAckReq::clear_servermsgid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.servermsgid_.ClearToEmpty();
}
inline const std::string& AddPendingOfflineAckReq::servermsgid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:push.AddPendingOfflineAckReq.serverMsgID)
  return _internal_servermsgid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AddPendingOfflineAckReq::set_servermsgid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.servermsgid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:push.AddPendingOfflineAckReq.serverMsgID)
}
inline std::string* AddPendingOfflineAckReq::mutable_servermsgid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_servermsgid();
  // @@protoc_insertion_point(field_mutable:push.AddPendingOfflineAckReq.serverMsgID)
  return _s;
}
inline const std::string& AddPendingOfflineAckReq::_internal_servermsgid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.servermsgid_.Get();
}
inline void AddPendingOfflineAckReq::_internal_set_servermsgid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.servermsgid_.Set(value, GetArena());
}
inline std::string* AddPendingOfflineAckReq::_internal_mutable_servermsgid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.servermsgid_.Mutable( GetArena());
}
inline std::string* AddPendingOfflineAckReq::release_servermsgid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:push.AddPendingOfflineAckReq.serverMsgID)
  return _impl_.servermsgid_.Release();
}
inline void AddPendingOfflineAckReq::set_allocated_servermsgid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.servermsgid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.servermsgid_.IsDefault()) {
    _impl_.servermsgid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:push.AddPendingOfflineAckReq.serverMsgID)
}

// int64 seq = 3;
inline void AddPendingOfflineAckReq::clear_seq() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seq_ = ::int64_t{0};
}
inline ::int64_t AddPendingOfflineAckReq::seq() const {
  // @@protoc_insertion_point(field_get:push.AddPendingOfflineAckReq.seq)
  return _internal_seq();
}
inline void AddPendingOfflineAckReq::set_seq(::int64_t value) {
  _internal_set_seq(value);
  // @@protoc_insertion_point(field_set:push.AddPendingOfflineAckReq.seq)
}
inline ::int64_t AddPendingOfflineAckReq::_internal_seq() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.seq_;
}
inline void AddPendingOfflineAckReq::_internal_set_seq(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seq_ = value;
}

// -------------------------------------------------------------------

// AddPendingOfflineAckResp

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace push


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // push_2eproto_2epb_2eh
