// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: push.proto

#include "push.pb.h"
#include "push.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace push {

static const char* PushService_method_names[] = {
  "/push.PushService/PushMsg",
  "/push.PushService/DelUserPushToken",
};

std::unique_ptr< PushService::Stub> PushService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PushService::Stub> stub(new PushService::Stub(channel, options));
  return stub;
}

PushService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_PushMsg_(PushService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DelUserPushToken_(PushService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PushService::Stub::PushMsg(::grpc::ClientContext* context, const ::push::PushMsgReq& request, ::push::PushMsgResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::push::PushMsgReq, ::push::PushMsgResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushMsg_, context, request, response);
}

void PushService::Stub::async::PushMsg(::grpc::ClientContext* context, const ::push::PushMsgReq* request, ::push::PushMsgResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::push::PushMsgReq, ::push::PushMsgResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushMsg_, context, request, response, std::move(f));
}

void PushService::Stub::async::PushMsg(::grpc::ClientContext* context, const ::push::PushMsgReq* request, ::push::PushMsgResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushMsg_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::push::PushMsgResp>* PushService::Stub::PrepareAsyncPushMsgRaw(::grpc::ClientContext* context, const ::push::PushMsgReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::push::PushMsgResp, ::push::PushMsgReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushMsg_, context, request);
}

::grpc::ClientAsyncResponseReader< ::push::PushMsgResp>* PushService::Stub::AsyncPushMsgRaw(::grpc::ClientContext* context, const ::push::PushMsgReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushMsgRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PushService::Stub::DelUserPushToken(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq& request, ::push::DelUserPushTokenResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::push::DelUserPushTokenReq, ::push::DelUserPushTokenResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DelUserPushToken_, context, request, response);
}

void PushService::Stub::async::DelUserPushToken(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq* request, ::push::DelUserPushTokenResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::push::DelUserPushTokenReq, ::push::DelUserPushTokenResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DelUserPushToken_, context, request, response, std::move(f));
}

void PushService::Stub::async::DelUserPushToken(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq* request, ::push::DelUserPushTokenResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DelUserPushToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::push::DelUserPushTokenResp>* PushService::Stub::PrepareAsyncDelUserPushTokenRaw(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::push::DelUserPushTokenResp, ::push::DelUserPushTokenReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DelUserPushToken_, context, request);
}

::grpc::ClientAsyncResponseReader< ::push::DelUserPushTokenResp>* PushService::Stub::AsyncDelUserPushTokenRaw(::grpc::ClientContext* context, const ::push::DelUserPushTokenReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDelUserPushTokenRaw(context, request, cq);
  result->StartCall();
  return result;
}

PushService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PushService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PushService::Service, ::push::PushMsgReq, ::push::PushMsgResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PushService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::push::PushMsgReq* req,
             ::push::PushMsgResp* resp) {
               return service->PushMsg(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PushService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PushService::Service, ::push::DelUserPushTokenReq, ::push::DelUserPushTokenResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PushService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::push::DelUserPushTokenReq* req,
             ::push::DelUserPushTokenResp* resp) {
               return service->DelUserPushToken(ctx, req, resp);
             }, this)));
}

PushService::Service::~Service() {
}

::grpc::Status PushService::Service::PushMsg(::grpc::ServerContext* context, const ::push::PushMsgReq* request, ::push::PushMsgResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PushService::Service::DelUserPushToken(::grpc::ServerContext* context, const ::push::DelUserPushTokenReq* request, ::push::DelUserPushTokenResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace push

