syntax = "proto3";

package auth;

service AuthService {
  rpc Register(RegisterRequest) returns (AuthResponse);
  rpc Login(LoginRequest) returns (AuthResponse);
  rpc ValidateToken(ValidateTokenReq) returns (ValidateTokenResp);
}

message RegisterRequest {
  string phone = 1;
  string nickname = 2;
  string password = 3;
}

message LoginRequest {
  uint64 account = 1;
  string password = 2;
}

message ValidateTokenReq {
  string token = 1;
}

message ValidateTokenResp {
  bool valid = 1;
  uint64 userID = 2;
  uint64 account = 3;
  int64 expiresAt = 4;
}

message AuthUser {
  uint64 userID = 1;
  uint64 account = 2;
  string nickname = 3;
  string phone = 4;
}

message AuthResponse {
  bool success = 1;
  string errorCode = 2;
  string errorMessage = 3;
  string token = 4;
  int64 expiresAt = 5;
  AuthUser user = 6;
}